### ISSUE TITLE
sendwhatmsg_to_group close tab too fast

### ISSUE THREAD

**Issue by IESKids** [Ankit404butfound/PyWhatKit#102]
When using **sendwhatmsg_to_group** and setting the tab to close after send, the message appears on in the web.whatsapp page, but never sends to the phone.  When tabs are not closed everything works fine.  There is an extra dialogue popping up in windows but it's too fast for me to catch before the tab closes.

````
`pysend.sendwhatmsg_to_group(gId, message, hourtosnd, mintosnd, 25, True, False)
```` 
`will send the message and leave tabs open.

````
`pysend.sendwhatmsg_to_group(gId, message, hourtosnd, mintosnd, 25, True, True) 
````
`closes the tab after writing the message but before it is sent from the phone.

I'm using:
Windows
Google Chrome  - Version 91.0.4472.164 (Official Build) (64-bit)
Python 3.8.5

**Comment by aaryanrr** [comment]
Hey @IESKids , we'll release an update shortly with the option to configure tab closing time. Thanks for reporting this.

**Comment by IESKids** [comment]
Thanks for being on it.

😀
