### ISSUE TITLE
Message not sending using sendwhatmsg_to_group

### ISSUE THREAD

**Issue by apoorvthedude** [Ankit404butfound/PyWhatKit#104]
**Describe the Bug**

Hi,I used kit.sendwhatmsg_to_group command to send message to whatsapp group.
I have given wait_time: 30  and close time: 5.
All the thing is working fine from opening it at the scheduled time but after opening it is not opening that group not writing the message in text box and not sending them.It is closing web.whatsapp.com at the scheduled time I have written in the code.

**Expected Behavior**

Expected Behaviour is after you write the commands in ide or text editor,web.whatsapp.com will open and then desired whatsapp group will open and message that you want to send will be written in the text box and message will be sent according what wait_time you have given and the tab will close according to close_tab time.

**Screenshots**

**Desktop (please complete the following information)**

- OS: [e.g. Ubuntu]
- Browser: [e.g. chrome]

**Python (please complete the following information)**

- Version: [e.g. 3.8.10]

**Additional Context**
I have written all the commands properly & have tried on more than one whatsapp group but facing same issue on all the groups.

**Comment by aaryanrr** [comment]
Hey @apoorvthedude , can you please share the code that you are using to call the function.

**Comment by apoorvthedude** [comment]
import pywhatkit as kit
kit.sendwhatmsg_to_group("group id","Message",time:in hr,time:in min,wait_time:30,True,close_tab:10)

## I can send whatsapp msg to individual using pywhatkit,but not able to send to whatsapp groups.

**Comment by apoorvthedude** [comment]
All commands are working fine,but it opens only the whatsapp main page not even that group and does not send the message to that group.
I have already written about the problem in the above thread/messages.

**Comment by aaryanrr** [comment]
Please make sure that the Group ID is correct. And also have a look at the URL bar of the browser when WhatsApp Web is opening to see if the URL Is formed correctly or not.

**Comment by apoorvthedude** [comment]
Group ID is correct,I'll look at the URL bar in the browser,but if i have written the code properly then how it depends with URL formed,I mean URL will automatically formed right.

**Comment by aaryanrr** [comment]
Try upgrading your installation to the latest version. And please share the way you are calling the function, just remove the group id and message from it and share the rest.

**Comment by sanilpandit** [comment]
Just a note: groupid is not Group name; groupid is the specific id you can find in the link you send to invite  someone in a group . for eg:https://chat.whatsapp.com/AbcDeFG28K where "AbcDeFG28K" is the groupid

**Comment by aaryanrr** [comment]
Hey @apoorvthedude, this bug has been fixed in the new version (5.2) which will be released by tomorrow. Thanks for reporting this.
