### ISSUE TITLE
doesn't allows to set the timer to 1am

### ISSUE THREAD

**Issue by perrilobi** [Ankit404butfound/PyWhatKit#107]
if u try to put the hour into 1 or 01, it sends Error

it should allow to set it up into that time

- OS: [MacOs]
- Browser: [safari]

- Version: [3.9]

**Comment by aaryanrr** [comment]
Hey @perrilobi , Thanks for reporting this. We'll verify this on our end and will update you.

**Comment by aaryanrr** [comment]
We have tested it on our end and it is working without any problems. Please make sure that you are using the latest version. Also, can you share the Error Message that it gives.
