### ISSUE TITLE
Send Message without opening window

### ISSUE THREAD

**Issue by jaydip-c** [Ankit404butfound/PyWhatKit#108]
Is it possible to send the message without opening the browser tab? It will just send the message at particular time from python console, without opening any browser?

Thanks.

**Comment by aaryanrr** [comment]
Hey @jaydip-c , This is not possible in PyWhatKit as WhatsApp doesn't provide any API to interact with. I think it is possible through selenium and using headless chrome but I don't know much about that.

**Comment by codewithpom** [comment]
@aaryanrr I have already done this we can do this in the next update using selenium.

**Comment by aaryanrr** [comment]
We don't want to use selenium with this library any more. We are thinking of another version of PyWhatKit using selenium in the future.
