### ISSUE TITLE
Not sending image with sendwhats_image

### ISSUE THREAD

**Issue by illives** [Ankit404butfound/PyWhatKit#109]
I am using python 3.8.7 version and pywhatkit==5.1.
When I try to send an image, only the text goes.

I am using windows 10.

pwk.sendwhats_image("+551197xxxxxxxxx", "D:\\path\\testewhatkit.jpg", "Here is the image", 10, True, 5)

**Comment by aaryanrr** [comment]
Hey @illives , try to pass on the path like this `"D:\\path\\image.jpg"` as `\` is a special character and you need to escape it. Also, try to clear your browser cache and login again.

**Comment by gaurav-gvd** [comment]
hello.. 
i get value error: "ValueError: conversion from RGB to RBG not supported" while sending image
the image in in jpg format

**Comment by aaryanrr** [comment]
Please upgrade your installation to the latest version.

**Comment by gaurav-gvd** [comment]
@aaryanrr thank you. issue solved.

**Comment by illives** [comment]
> Hey @illives , try to pass on the path like this `"D:\\path\\image.jpg"` as `\` is a special character and you need to escape it. Also, try to clear your browser cache and login again.


unfortunately it didn't work.
With one image the test was successful, but when I placed another image only the text was sent.
And no errors were raised by python.

pwk.sendwhats_image("+551197xxxxxxx", "D:\\R_DELFOS_PREVISAO_MOBILE\\My_Pictures\\chart01.png", "Here is the image", 10, True, 5)

**Comment by aaryanrr** [comment]
> > Hey @illives , try to pass on the path like this `"D:\\path\\image.jpg"` as `\` is a special character and you need to escape it. Also, try to clear your browser cache and login again.
> 
> 
> unfortunately it didn't work.
> With one image the test was successful, but when I placed another image only the text was sent.
> And no errors were raised by python.
> 
> pwk.sendwhats_image("+551197xxxxxxx", "D:\\\R_DELFOS_PREVISAO_MOBILE\\\My_Pictures\\\chart01.png", "Here is the image", 10, True, 5)

Can you try it again by placing the image in the same directory as of the script. Also, Is this error with a particular format of image?

**Comment by kue5573** [comment]
Hi Sir... i have also has the same issue.. I use latest pywhatkit==5.1. but no image upload and not able to send the message.. i already change wait time >30s .. but still no respond and I am using windows 10.  Can anyone advise how to fix the bugs...

**Comment by aaryanrr** [comment]
Hey @kue5573, this bug has been fixed in version 5.2. It will be released by tomorrow!

**Comment by kue5573** [comment]
Thanks a lot.. I am really excited to use it.

**Comment by Costosmaya** [comment]
hi there, it says you were going to release a new version to fix this bug but where still in version 5.1, i'm having this issue, not sending the image just text.

**Comment by aaryanrr** [comment]
Hey @Costosmaya, we apologize for the delay in update. All the core maintainers are currently busy with other stuff and there are a lot of changes that have to be finalized for the next update. Thanks for bearing with us.

**Comment by aaryanrr** [comment]
Hey @illives , this bug has been fixed in #123. The update will be released today. Thank you!

**Comment by jamesbcn** [comment]
I am having the same problem. 

I am using 2.3.1 

Python 3.10.1

No errors. There is, however, an error when I intentionally write the path incorrectly.

**Comment by jamesbcn** [comment]
I am having the same problem. 

I am using 2.3.1 

Python 3.10.1

No errors. There is, however, an error when I intentionally write the path incorrectly.

**Comment by infocus619** [comment]
import pywhatkit as pwk

pwk.sendwhats_image(phone_no="+917904*******", img_path="C:/User/MI/OneDrive/Desktop/thubel.png", caption="Example image sent!")
error:AttributeError: partially initialized module 'socket' has no attribute 'AF_INET' (most likely due to a circular import)

**Comment by SigireddyBalasai** [comment]
this error will be resolved in the next release you can use asyncpyewhatkit in mean time

**Comment by Enemfu** [comment]
Hi...I also spent quite some time trying to solve this same problem. In my case, two details helped me.
I hope it helps you too.
1º I put the full path, exactly this way below:
r "C:\u003d\u003d\u003d\u003d\inves.png"
2º includes the complete path of the image with the backslash, the letter 'r', and just below the line of WhatsApp code I put the timesleep(5), like this:
pywhatkit.sendwhats_image("+3532498XXXX39" , r "C:\Users\Cliente\ipynb\inves.png")
time.sleep(5)

**Comment by Enemfu** [comment]
Hi...I also spent quite some time trying to solve this same problem. In my case two details helped me.
I hope it helps you too.

1º I put the full path, exactly this way below:
r "C:\\u003d\u003d\u003d\u003d\inves.png"

2º includes the complete path of the image with the backslash, the letter 'r' and just below the line of whatsapp code I put the timesleep(5), like this:

pywhatkit.sendwhats_image("+3532498XXXX39" ,r "C:\\Users\Cliente\ipynb\inves.png")
time.sleep(5)

**Comment by khogula2004** [comment]
Hello @Costosmaya. I have installed latest pywhatkit version 5.4 but it is showing an error that unable to access pywhatkit api right now

**Comment by quotingsmoldering** [comment]
> Hello [@Costosmaya](https://github.com/Costosmaya). I have installed latest pywhatkit version 5.4 but it is showing an error that unable to access pywhatkit api right now





https://poutkieran.github.io/WTZlqNMoCB07oZxkSRGQ0dbDmFpUqVE2S2QPcC3m67sR0NDdd3c10EGLll/
