### ISSUE TITLE
chrom not open 

### ISSUE THREAD

**Issue by GreenAA** [Ankit404butfound/PyWhatKit#110]
Hi thanks 

i have win 10 

**after i run the script , the chrom nt open ,** 
import pywhatkit
pywhatkit.sendwhatmsg("phone num", time_hour=20, time_min=30, message="hi bro")

**prompet :** 
and this is the message -In 24030 seconds web.whatsapp.com will open and after 20 seconds message will be delivered

**Comment by aaryanrr** [comment]
Please make sure that you are passing on the Time correctly. Have a look [here](https://github.com/Ankit404butfound/PyWhatKit/wiki/Sending-WhatsApp-Messages) for documentation.

**Comment by GreenAA** [comment]
thanks bro


‫בתאריך יום ג׳, 24 באוג׳ 2021 ב-17:24 מאת ‪aryan‬‏ <‪
***@***.***‬‏>:‬
