### ISSUE TITLE
Like to add a QRCODE recognition feature

### ISSUE THREAD

**Issue by akpythonyt** [Ankit404butfound/PyWhatKit#112]
Pywhatkit contains some exciting features, So I like to add this feature to it,

FEATURE EXPLAINED:
Using the OCR techniques and Opencv like to add this feature to pywhatkit.

**Comment by aaryanrr** [comment]
Hey @akpythonyt , Thanks for considering contributing to this project. We are currently not planning to include this as adding `opencv` to the install requirements would increase the install time and we really wanted this library to be light weight. You can have a look at the next version board under projects to look for possible feature's to implement. Thanks
