### ISSUE TITLE
Envio de mensaje a grupos

### ISSUE THREAD

**Issue by isaias94** [Ankit404butfound/PyWhatKit#115]
Estoy intentando enviar un mensaje a un grupo de Whatsapp, este me abre la ventana del grupo, pero no pega el mensaje......

**Comment by aaryanrr** [comment]
Hey @isaias94 , Please make sure you are using the latest version of the library (5.1). And please don't use your mouse or keyboard while the script is running. Please confirm if any of this fixes the issue.

**Comment by isaias94** [comment]
Hello, the version is the latest (5.1), but it still won't let me send the message, this a example.

import pywhatkit as kit

kit.sendwhatmsg_to_group('XXXXXXXXXX','Hi this is a bot',0,2,20)

**Comment by aaryanrr** [comment]
Follow these Steps:
1. Open the `main.py` file under the directory where `PyWhatKit` is installed. If you are using a virtual environment than this should be under `venv/lib/pywhatkit`.
2. Navigate to the function declaration of `sendwhatmsg_to_group`.
3. Comment this line out inside the function
```py
pg.click(width / 2, height / 2)
```

**Comment by jlberlanga** [comment]
I have the same problem, it opens the chat group put doesn't paste the text, then it close the tab without problem

**Comment by aaryanrr** [comment]
Hey @isaias94 and @jlberlanga, this bug has been fixed in #123. The update will be released today. Thank you!
