### ISSUE TITLE
Translator Feature

### ISSUE THREAD

**Issue by Sachit71** [Ankit404butfound/PyWhatKit#117]
**Is your feature request related to a problem? Please describe.**
Since PyWhatkit is a versatile module, a translator function/feature would be helpful.
**Describe the solution you'd like**
I plan on using the deep-translator package for this

**Describe alternatives you've considered**
I'd like to know your opinion on this.

**Additional context**

**Comment by aaryanrr** [comment]
Hi @Sachit71, thank you for your valuable suggestion. But we are not planning to include this feature as it doesn't seem relevant to the purpose of this library.

**Comment by codewithpom** [comment]
@aaryanrr I can make a Flask web server with the deep-translate or even this [https://pypi.org/project/gtran/](gtrans) and I have plenty of time and even making a web server will affect the size of the package very much. Thank you for your suggestion @Sachit71
