### ISSUE TITLE
Vscode not linting sendwhatmsg_instantly()

### ISSUE THREAD

**Issue by jramosss** [Ankit404butfound/PyWhatKit#118]
**Describe the Bug**
Whenever i try to import the function as
`from pywhatkit import sendwhatmsg_instantly`
or
`import pywhatkit as kit`
`kit.sendwhatmsg_instantly()`
it appears like the function does not exist, when i execute the program it works, but i don`t receive any autocompletion or info about the function.

i receive this error
**To Reproduce**
1 - create a venv and activate
2 - install the package with pip
3 - create a file, import the function as i said 
4 - start to write

**Expected Behavior**
Receive info and autocompletion just like the other functions of the library

**Screenshots**
![When Importing](https://i.imgur.com/yUfryqx.png)
![When Writing](https://i.imgur.com/yyFnozE.png)
When writing, it appears like an atribute (any), not a function

**Desktop (please complete the following information)**

- OS: [Linux, Ubuntu]
- Browser: [Chrome]
- Version: [92.0.4515.159]

**Python (please complete the following information)**

- Version: [3.8.5]

**Comment by aaryanrr** [comment]
Hey @jramosss, Please make sure you are using the latest version of PyWhatKit (5.1)

**Comment by jramosss** [comment]
I am, i did pip freeze and got pywhatkit==5.1

**Comment by aaryanrr** [comment]
We have tested it on our end and it is working as expected. Can you open the `__init__.py` file to verify the presence of this line
```py
from pywhatkit.main import sendwhatmsg_instantly, ...
```
It should be present under `venv/lib/pywhatkit`.

**Comment by jramosss** [comment]
It is present, linted as it wasnt a function 
![a](https://i.imgur.com/RYSJNzJ.png)

**Comment by jramosss** [comment]
I found the solution, i wasnt using the venv enviroment in vscode.
