### ISSUE TITLE
It opened the Whatsapp with the text but didn't send automatically.

### ISSUE THREAD

**Issue by eddieonthego** [Ankit404butfound/PyWhatKit#122]
It opened the Whatsapp with the text but didn't send automatically.

pywhatkit.sendwhatmsg_instantly('+60183546457', 'Hello Testing Pywhatkit')

**Comment by eddieonthego** [comment]
it did sent but only after a while.

**Comment by aaryanrr** [comment]
Hey @eddieonthego, there is a wait time before the message is sent. For sending messages instantly, you can use the `sendwhatmsg_instantly` function. Thanks
