### ISSUE TITLE
Get website screenshot without using chromedriver, beautifulsoup or any other scraping packages

### ISSUE THREAD

**Issue by Sachit71** [Ankit404butfound/PyWhatKit#128]
**Is your feature request related to a problem? Please describe.**
Nope, Since PyWhatkit revolves around web scraping and data extraction, I think this feature would be really helpful.

**Describe the solution you'd like**
This website that I found helps take a screenshot of the mentioned link, link entered as an arg

**Describe alternatives you've considered**
The website/software is render-tron a headless chrome rendering solution.
https://github.com/GoogleChrome/rendertron

**Additional context**
If this feature is approved, I'd like to make a pull request.
Discord: cyber#7596

**Comment by codewithpom** [comment]
yes @Sachit71 we will surely work on this feature and my name is Padmashree and now I will send you a friend request on discord to talk there.
