### ISSUE TITLE
Using Telegram instead of WhatsApp

### ISSUE THREAD

**Issue by twozero88** [Ankit404butfound/PyWhatKit#131]
**Is your feature request related to a problem? Please describe.**
Yes. WhatsApp does not have an open API access, making us take complex approaches for very simple tasks as well.

**Describe the solution you'd like**
Using telegram instead.

**Describe alternatives you've considered**
Telegram/Discord

**Additional context**
Going against the name of PyWhatKit, but Telegram would work much better.

I could work on migrating basic features to Telegram.

**Comment by codewithpom** [comment]
but why ???? there are already modules for telegram.

**Comment by codewithpom** [comment]
@twozero88 Here are some modules for telegram
- https://pypi.org/project/telegram/

**Comment by Naman23-coder** [comment]
@aaryanrr can please close this issue?
