### ISSUE TITLE
Upgrading the existing feature Text To Handwriting.

### ISSUE THREAD

**Issue by Tanish-Panwar** [Ankit404butfound/PyWhatKit#133]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [This would make the existing feature more easy to use just by using voice]

**Describe the solution you'd like**
I have already made it using speech_reco. This feature is too simple

**Describe alternatives you've considered**

**Additional context**

**Comment by aaryanrr** [comment]
Hey @Tanish-Panwar, thanks for the valuable suggestion. There are already a lot of wrappers available for the Telegram API which are really easy to use and are well documented whereas this is not the case with WhatsApp so that's why we are trying to fill this gap.

**Comment by Tanish-Panwar** [comment]
@aaryanrr  
[](https://github.com/Tanish-Panwar/Speech-To-Handwriting./blob/main/Speech_To_Handwriting.py)
You may test it out , we can make it much better , 
This needs network that makes it little bit slow, but this can be fixed

**Comment by codewithpom** [comment]
@Tanish-Panwar Thanks for your effort and now I am going to check your repository maybe it's name is Speech-To-Handwriting.

(https://github.com/Tanish-Panwar/Speech-To-Handwriting)[https://github.com/Tanish-Panwar/Speech-To-Handwriting]

**Comment by Tanish-Panwar** [comment]
@codewithpom  
have you checked it

**Comment by codewithpom** [comment]
@Ankit404butfound Tanish wants to add speech recognition in it.

**Comment by Tanish-Panwar** [comment]
OK. 😊 It was a great pleasure to talk with experts in industry.
