### ISSUE TITLE
The Content Security Policy directive 'upgrade-insecure-requests' is ignored when delivered in a report-only policy

### ISSUE THREAD

**Issue by Costosmaya** [Ankit404butfound/PyWhatKit#139]
Hi, i have been trying to use the sendwhats_image method to send some automated imgs with windows task scheduler. But every time the script is executed, i get this error on the browsers console "The Content Security Policy directive 'upgrade-insecure-requests' is ignored when delivered in a report-only policy." Tried clearing cache but didn't do anything, also in the python console seems to be no problem as starts and ends the execution with no problems. I wanted to know there's a work around for this. 

Also now that i cleared the cache, shows me this error too.
`Uncaught (in promise) TypeError: Failed to execute 'put' on 'Cache': Partial response (status code 206) is unsupported
    at serviceworker.js:1
    at Generator.next (<anonymous>)
    at c (serviceworker.js:1)
    at o (serviceworker.js:1)`

**Comment by aaryanrr** [comment]
I am closing this issue as their is no further update on this.
