### ISSUE TITLE
Free SMS using fast2sms api

### ISSUE THREAD

**Issue by Sachit71** [Ankit404butfound/PyWhatKit#143]
## Fast2SMS 

This is an useful API that let's users send SMS to the mentioned phone number for free, it's limits for free usage is 20 requests per day.

I think this can be a really good feature for the pywhatkit package.

## Feature Description
It simply uses the requests module to communicate with the api and boom, your done, no additional dependencies are required.

If this issue is verified, I can go ahead and request for merging my pr in which the code is implemented.

**Comment by Sachit71** [comment]
Also it isn't clear if this API works only in India or works for international numbers too, we'll have to test that.

**Comment by aaryanrr** [comment]
Hey @Sachit71, thanks for you continue contributions. I have asked the core maintainers and contributors about this. You'll be updated accordingly.

**Comment by aaryanrr** [comment]
Hey Sachi, so I have discussed it with other contributors and we feel that there won't be much use of this function as it requires someone to register with a service. Hope you understand :)

**Comment by Sachit71** [comment]
Oh yeah totally understandable, I will be closing the issue now.

**Comment by aaryanrr** [comment]
Thanks sachit!
