### ISSUE TITLE
Ability to read messages from chat

### ISSUE THREAD

**Issue by bkstephen** [Ankit404butfound/PyWhatKit#145]
To create a fully automated library which can e.g. easily be used as the foundation library to build a text bot, as a developer I should be able to also have the ability to read messages in order to processes them in any way I think is fitting.

The library could have a 2 new  methods: `readmsg()` and `readmsg_from_group()` which could functionally operate similarly to how the `sendmsg()` methods do by opening a browser to the specified window and parsing the html elements to retrieve messages send in that chat. A parameter could be passed to those methods specifying the time range during which the messages should be retrieved.

**Comment by codewithpom** [comment]
@bkstephen We need selenium for that and we cannot use it as we want to keep our module light but we are working on it already.

**Comment by aaryanrr** [comment]
Hey @bkstephen, thanks for the valuable suggestion. To be able to read the messages from a chat we'll need to use selenium only. We want this library to be ready to use after installation without needing any extra setup or files to be downloaded so its not possible to add this feature.
