### ISSUE TITLE
Run pywhatkit in background

### ISSUE THREAD

**Issue by BismeetSingh** [Ankit404butfound/PyWhatKit#148]
Is there a way to send messages without invoking the whatsapp front end? I want my messages to be scheduled and sent to a particular group in the background,

**Comment by aaryanrr** [comment]
Hey @BismeetSingh.  This library automates the GUI to send messages which is not possible without opening the Web App. There are several other libraries which use selenium to automate it in a headless way.

**Comment by BismeetSingh** [comment]
Okay, I got it to work using https://whatsmate.github.io/
