### ISSUE TITLE
Image Loads with Caption and Without But not sent

### ISSUE THREAD

**Issue by 00war10ck00** [Ankit404butfound/PyWhatKit#153]
## Description

Image Not Sent

## To Reproduce

Use sendwhats_image to send an image to group or contact

## Version Information

- OS: [e.g. Windows 10]
- Browser: [e.g. Mozilla Firefox, Google Chrome]
- Python: [e.g. 3.9.6]
- PyWhatKit: [e.g. 5.2]

**Comment by aaryanrr** [comment]
Hey @00war10ck00, this is a duplicate of #152 so I am closing this.
