### ISSUE TITLE
Can i use sendwhatmsg without using time_hour and time_min arguments? 

### ISSUE THREAD

**Issue by httpanand** [Ankit404butfound/PyWhatKit#154]
Can i use sendwhatmsg without using time_hour and time_min arguments?  i.e , Is it possible to send the message at the time of execution itself ?

**Comment by codewithpom** [comment]
@httpanand Thanks for the feature request and I would like you to suggest the datetime module to get current hour and minute :slightly_smiling_face: .

**Comment by Ankit404butfound** [comment]
You can also use sendwhatmsg_instantly() function.

**Comment by httpanand** [comment]
> You can also use sendwhatmsg_instantly() function.

oohk thanks <3 Is there any docs written for this function  ?

**Comment by Ankit404butfound** [comment]
Yes, please check this, https://github.com/Ankit404butfound/PyWhatKit/wiki/Sending-WhatsApp-Messages.

**Comment by httpanand** [comment]
Thanks <3
