### ISSUE TITLE
sendwhatmsg_to_group() does not work properly

### ISSUE THREAD

**Issue by aaronwtr** [Ankit404butfound/PyWhatKit#155]
## Description
I have been using this function for weeks now to send a message to a groupchat automatically each week. It was working fine up to this week. It looks like it is something from WhatsApp side that is messing it up. The link that shows up in the searchbar is: https://web.whatsapp.com/accept?code=WA_GROUP_KEY where WA_GROUP_KEY is the key to the WhatsApp group. In a second, this link changes into https://web.whatsapp.com and I get loaded into web WhatsApp and not the correct group. Consequently, the pre-programmed messaged can't be sent since it does not have access to the groupschat. 

## To Reproduce

Use the sendwhatmsg_to_group() to send any message to a WhatsApp groupschat. The group_key can be obtained from the invite URL the host of the WhatsApp group can generate. 

## Screenshots

If applicable, add Screenshots to help explain your Problem

## Version Information

- OS: Windows 10 64-bit
- Browser: Google Chrome
- Python: 3.7
- PyWhatKit: 5.1

You can Check the PyWhatKit Version using

```py
print(pywhatkit.__VERSION__)
```

**Comment by Naman23-coder** [comment]
@aaronwtr please send a screenshot

**Comment by aaronwtr** [comment]
What specifically do you want a screenshot of? My code or what I am observing in the browser? It would be difficult to screenshot the latter since it happens in a split second and I described what happens in detail in my explanation. > @aaronwtr please send a screenshot

**Comment by aaronwtr** [comment]
@Naman23-coder What specifically do you want a screenshot of? My code or what I am observing in the browser? It would be difficult to screenshot the latter since it happens in a split second and I described what happens in detail in my explanation.

**Comment by Naman23-coder** [comment]
@aaronwtr send a screenshot when the tab opens

**Comment by aaronwtr** [comment]
@Naman23-coder I do not see any added value in sharing screenshots of what is the start screen of web whatsapp.  I observe for a split second that it is trying to enter the group chat, as explained in my main post, and then it does not enter the group chat and just remains in the web whatsapp start screen in which all the recent chats are ordered on the left and on the right is a big empty space where the chat would be if opened.

**Comment by Naman23-coder** [comment]
@aaronwtr please use `pip install pywhatkit --upgrade` if you are not using pywhatkit latest version

**Comment by zarif98sjs** [comment]
I am having the same issue. 
`The link that shows up in the searchbar is: https://web.whatsapp.com/accept?code=WA_GROUP_KEY where WA_GROUP_KEY is the key to the WhatsApp group. In a second, this link changes into https://web.whatsapp.com and I get loaded into web WhatsApp and not the correct group.`

**Comment by Naman23-coder** [comment]
@zarif98sjs this is on WhatsApp side,we'll check it soon

**Comment by Neotastisch** [comment]
Same here

**Comment by Naman23-coder** [comment]
Hey everyone it may be due to beta version (if you have one),try rolling back to stable release

**Comment by aaronwtr** [comment]
Indeed I was participating in the new beta. Unfortunately, rolling back to a web whatsapp version prior to the beta did not solve the problem. I look forward to updates on this issue!

**Comment by zarif98sjs** [comment]
@aaronwtr please check here https://github.com/zarif98sjs/PyWapp . I have worked on this and this works fine

**Comment by muhohokenya** [comment]
Same issue as @zarif98sjs  looking forward to getting a working solution

**Comment by CharlieBatchelor** [comment]
Once the WhatsApp page opens, clicking on the group continues the automation of message sending. So issue is opening the browser to the correct group chat rather than having WhatsApp sending us to https://web.whatsapp.com.

**Comment by aaryanrr** [comment]
Hey everyone, thanks for reporting this issue. Make sure you are not participating in the WhatsApp Beta. I have tested this function today on Linux with Chrome Browser and its working for me. If you are still facing this issue please don't hesitate to reach out to us.

**Comment by hDmtP** [comment]
Yeah!, it also works on Firefox(Linux)

**Comment by aaronwtr** [comment]
Thanks for looking at this issue! It is now working again with exactly the same setup as with which I reported the problem originally.
