### ISSUE TITLE
Send a msg to multiple contacts given a list of phone numbers

### ISSUE THREAD

**Issue by DevGab5** [Ankit404butfound/PyWhatKit#156]
## Feature Description

Send a single msg to multiple contacts from a list of phone numbers.

**Comment by aaryanrr** [comment]
Hey @DevGab5, thanks for the feedback. You can use a simple for loop to achieve this.
```py
import pywhatkit

nums = ["num1", "num2"]
for x in nums:
    pywhatkit.sendwhatmsg(x, "hi", 12, 12)
```
Hope this helps!

**Comment by MVerma44** [comment]
No this will not work.

**Comment by aaryanrr** [comment]
Hey @MVerma44, you'll have to use the `datetime` module to get the current hour and minute and perform the increment so this can work.

**Comment by JoelSmalls** [comment]
> Hey @MVerma44, you'll have to use the `datetime` module to get the current hour and minute and perform the increment so this can work.

When you say this what do you mean by that? As in I have to slow it down by using sleep? or include a hour and time within the hour and time section on the "sendwhatmsg" line? Because I tried what you gave to the other guy initially and it immediately fired up three separate instances of WhatsApp
