### ISSUE TITLE
Save QR code session info, so that user doesn't have to login everytime

### ISSUE THREAD

**Issue by Sachit71** [Ankit404butfound/PyWhatKit#158]
PyWhatKit works perfectly, but on the raspberry pi, I have to scan the QR code every time I switch on and run the device, can we make a folder such that it saves the QR session, this feature is also seen in https://github.com/shauryauppal/PyWhatsapp Pywhatsapp by shuarya, in this he makes a folder to store the qr session, I was wondering it would be awesome if pywhatkit could do the same.

**Comment by Sachit71** [comment]
They also seem to use chrome driver for logging in

**Comment by Naman23-coder** [comment]
But problem is that selenium is very heavy and pywhatkit is a light weight library

**Comment by aaryanrr** [comment]
Hey @Sachit71, thanks for the valuable suggestion. I don't think so there is any way to store the session information other than using selenium. We'll see if its possible or not.
