### ISSUE TITLE
 can I send a base64 image instead of the image path?

### ISSUE THREAD

**Issue by atilamagalhaes4** [Ankit404butfound/PyWhatKit#16]
b64 = "data:image/jpg;base64,///sdasdasda....."
ex: pywhatkit.send_file("+919876543210",b64",15,00).

**Comment by Ankit404butfound** [comment]
I haven't tested it, but it's worth a try.
Although I don't think it's going to work.
Let us know.😄

**Comment by aaryanrr** [comment]
Hey @atilamagalhaes4, You can use this
```py
import base64

img_data = "data:image/jpg;base64,///sdasdasda....."

IMAGE = img_data.split(",")
extension = IMAGE[0].split(";")
with open(f"Picture.{extension[0].split('/')[1]}", "wb") as f:
    f.write(base64.decodebytes(bytes(IMAGE[1], "utf-8")))
```

The picture will be first written to a file for which the extension will be determined by the data passed in. After that you can use the `sendwhats_image` function to send this file to the contact. Thanks
