### ISSUE TITLE
Unable to import pywhatkit

### ISSUE THREAD

**Issue by rvaquerizor** [Ankit404butfound/PyWhatKit#160]
## Description

When I try to import _pywhatkit_ on my project, I get always an error:
`NOTE: You must install tkinter on Linux to use MouseInfo. Run the following: sudo apt-get install python3-tk python3-dev
`
I already have _python3-tk python3-dev_ packages installed on my system.

## To Reproduce

Just include _import pywhatkit_ into a python script and try to execute the script.

## Screenshots

`NOTE: You must install tkinter on Linux to use MouseInfo. Run the following: sudo apt-get install python3-tk python3-dev
`
## Version Information

- OS: Ubuntu 21.10
- Browser: n/a
- Python: 3.10.0
- PyWhatKit: 5.2

You can Check the PyWhatKit Version using

```py
print(pywhatkit.__VERSION__)
```

**Comment by aaryanrr** [comment]
Hey @rvaquerizor, thanks for reaching out to us. As you are using python 3.10, you need to install `python3.10-tk` and `python3.10-dev` packages.

**Comment by rvaquerizor** [comment]
Thanks @aaryanrr for the prompt reply.

Turns out that _python3.10-tk_ is not a package recognized by apt:

```
❯ sudo apt install python3.10-tk
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'python3-tk' instead of 'python3.10-tk'
python3-tk is already the newest version (3.9.7-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded. 

```

On the other hand, I could install python3.10-dev successfully.

But I still get the same error:

`NOTE: You must install tkinter on Linux to use MouseInfo. Run the following: sudo apt-get install python3-tk python3-dev                                                            
`

Is there any special source that I have to add to my system so that python3.10-tk is found?

Thanks!

**Comment by aaryanrr** [comment]
I think `python3-tk` should do the job. Can you show me the command that you are using to run the script?

**Comment by Naman23-coder** [comment]
try:
`sudo apt-get install python3-tk`

**Comment by rvaquerizor** [comment]
@aaryanrr 
It is a very basic poetry project, using the following pyproject.toml:
```
❯ cat pyproject.toml
[tool.poetry]
name = "pwk"
version = "0.1.0"
description = "test"
authors = ["XXXXX <xxxxxxx@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
pywhatkit = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"                 
```
The content of the script is as follows:

```
❯ cat pwk.py
import pywhatkit

# Send a WhatsApp Message to a Contact at 1:30 PM
pywhatkit.sendwhatmsg("+XXXXXXXXXXX", "Hello world", 13, 30) 
```  


I execute it doing:
```
❯ python3.10 pwk.py
NOTE: You must install tkinter on Linux to use MouseInfo. Run the following: sudo apt-get install python3-tk python3-dev                 
```

@Naman23-coder 
That is already installed on my system:

```
❯ apt list python3-tk
Listing... Done
python3-tk/impish,now 3.9.7-1 amd64 [installed]
python3-tk/impish 3.9.7-1 i386                                                                                                                                                           /0,9s
❯ apt list python3.10-dev
Listing... Done
python3.10-dev/impish,now 3.10.0-2 amd64 [installed]
python3.10-dev/impish 3.10.0-2 i386 
```

**Comment by aaryanrr** [comment]
Can you try this command `python3.10 -c "import tkinter"`. If tkinter is installed, this should yield no errors.

**Comment by rvaquerizor** [comment]
@aaryanrr 
Here we go:

```
❯ python3.10 -c "import tkinter"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.10/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'  
```  

For some reason, my virtualenv does not seem to find the python3-tk package, which is already installed on my system.

**Comment by aaryanrr** [comment]
Try this:
`sudo apt remove python3-tk && sudo apt install python3.10-dev python3.10-tk`

**Comment by rvaquerizor** [comment]
@aaryanrr 
Still no luck:

```
❯ sudo apt remove python3-tk && sudo apt install python3.10-dev python3.10-tk

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  blt tk8.6-blt2.5
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  python3-tk
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 893 kB disk space will be freed.
Do you want to continue? [Y/n] 
(Reading database ... 326733 files and directories currently installed.)
Removing python3-tk:amd64 (3.9.7-1) ...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'python3-tk' instead of 'python3.10-tk'
python3.10-dev is already the newest version (3.10.0-2).
Suggested packages:
  tix python3-tk-dbg
The following NEW packages will be installed:
  python3-tk
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 112 kB of archives.
After this operation, 893 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://es.archive.ubuntu.com/ubuntu impish/main amd64 python3-tk amd64 3.9.7-1 [112 kB]
Fetched 112 kB in 0s (438 kB/s)    
Selecting previously unselected package python3-tk:amd64.
(Reading database ... 326695 files and directories currently installed.)
Preparing to unpack .../python3-tk_3.9.7-1_amd64.deb ...
Unpacking python3-tk:amd64 (3.9.7-1) ...
Setting up python3-tk:amd64 (3.9.7-1) ...                                                                                                                                               


❯ python3.10 -c "import tkinter"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.10/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'                           
```

**Comment by Naman23-coder** [comment]
@rvaquerizor try reinstalling python or using python official 3.9

**Comment by Naman23-coder** [comment]
>First, make sure you have python-support installed:
>sudo apt-get install python-support
Then, run update-python-modules with the -a option to rebuild all the modules:
>sudo update-python-modules -a

source:-[stackoverflow](https://stackoverflow.com/questions/6084416/tkinter-module-not-found-on-ubuntu)

**Comment by rvaquerizor** [comment]
@Naman23-coder 
You are right. There was a problem with my python3.10 installation.
I built it from source code and for some reason _tkinter did not get included.

After removing it and reinstalling it from apt repositories, I can import pywhatkit without any problem.

thanks.

**Comment by Naman23-coder** [comment]
@rvaquerizor no problem :-)

**Comment by walidsst** [comment]
the error hasn't been solved at all I'm running test on windows 10
`ModuleNotFoundError: No module named 'pywhatkit'`

**Comment by Naman23-coder** [comment]
@walidsst got to c://users/~username~/appdata/programs/python/libs/site packages
and check wether there is pywhatkit folder
