### ISSUE TITLE
[Question] Is It possible to send messages without opening the browser user interface?

### ISSUE THREAD

**Issue by gui1080** [Ankit404butfound/PyWhatKit#162]
Let's say, If I want to run `pywhatkit.sendwhatmsg` from a script that is in my CentOS server every once in a while, Is It possible to create a new argument to this function that runs `options.headless = True` from the webbrowser library? Would this be helpful in order to run scripts from server enviroments?

**Comment by aaryanrr** [comment]
Hey @gui1080, thanks for reaching out to us. The webbrowser library doesn't have the ability to create a headless instance of a browser. For this we'll have to use selenium. It will surely be helpful in server environments where in most cases users are interacting using a terminal.
