### ISSUE TITLE
Adding a feature play on spotify

### ISSUE THREAD

**Issue by freakflames29** [Ankit404butfound/PyWhatKit#168]
## Related Problem

Just like playonyt() plays the song on youtube how about playonspotify() to play song directly on spotify.

## Feature Description

If someone only want to listen to the audio version only of a mainly song video  it should be more appropriate to play the song on spotify.

**Comment by Naman23-coder** [comment]
@freakflames29 you can use a lib called spoti2py

**Comment by aaryanrr** [comment]
Hey @freakflames29, thanks for your valuable contribution. There are existing libraries for this purpose, you can use them for this purpose. Hope this resolves your query!
