### ISSUE TITLE
Sending messages asynchronously! 

### ISSUE THREAD

**Issue by OmarJazzar** [Ankit404butfound/PyWhatKit#169]
## Related Problem

One cannot send a message in two hours if he/she needs to close his/her laptop in 20 min! You know, the main thread has to keep on running until it is the desired time to send the message.

## Feature Description

It would be perfect to maintain an asynchronous whats message that can be sent later while you can just close the program and be home-free. I think this requires a side server that is responsible for storing and running these pre-stored requests :)
What do you think about this feature? Is it possible to implement this with the least amount of costs?

**Comment by aaryanrr** [comment]
Hey @OmarJazzar, thanks for reaching out. This is possible with a selenium based library as it can operate in a headless way on a server. I don't think so this is possible with PyWhatKit unless we shift to selenium.
