### ISSUE TITLE
Unable to remove pywhatkit from Raspberry Pi

### ISSUE THREAD

**Issue by kostrhount** [Ankit404butfound/PyWhatKit#174]
Hi,

I am trying to remove pywhatkit from Raspberry Pi and during the uninstallation process I get the error message "EOFError: EOF when reading a line".

Complete error message:

> Proceed (y/n)? ERROR: Exception:
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 223, in _main
>     status = self.run(options, args)
>   File "/usr/lib/python3/dist-packages/pip/_internal/commands/uninstall.py", line 89, in run
>     uninstall_pathset = req.uninstall(
>   File "/usr/lib/python3/dist-packages/pip/_internal/req/req_install.py", line 694, in uninstall
>     uninstalled_pathset.remove(auto_confirm, verbose)
>   File "/usr/lib/python3/dist-packages/pip/_internal/req/req_uninstall.py", line 397, in remove
>     if auto_confirm or self._allowed_to_proceed(verbose):
>   File "/usr/lib/python3/dist-packages/pip/_internal/req/req_uninstall.py", line 440, in _allowed_to_proceed
>     return ask('Proceed (y/n)? ', ('y', 'n')) == 'y'
>   File "/usr/lib/python3/dist-packages/pip/_internal/utils/misc.py", line 247, in ask
>     response = input(message)
> EOFError: EOF when reading a line

Is this a bug or is there a workaround?

Steps to reproduce:
pip uninstall pywhatkit
sudo pip uninstall pywhatkit
python -m pip uninstall pywhatkit
-- all returns the same error

- OS: Raspbian GNU/Linux 11 (bullseye)
- Python: 3.9

Thank you for the advice,
Tomas

**Comment by Naman23-coder** [comment]
@kostrhount 
Try
`pip install pip --upgrade`
Or
`pip install pipwin`
`pip uninstall pip`
`pipwin install pip`

**Comment by Naman23-coder** [comment]
@kostrhount this might be because you didn't gave a response to `Proceed:(Y/N)`

**Comment by Naman23-coder** [comment]
Just write `Y` as a response

**Comment by kostrhount** [comment]
@Naman23-coder thank you for the advice, although I do not get the chance to give a response (`Y`)
The error is raised without asking for input.

**Comment by Naman23-coder** [comment]
@kostrhount 
Try
`pip install pip --upgrade`
Or
`pip install pipwin`
`pip uninstall pip`
`pipwin install pip`

**Comment by aaryanrr** [comment]
@kostrhount Is this issue resolved now?

**Comment by Manojwithcode** [comment]
File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pywhatkit/init.py"
bhai ye problem solve nahi ho rahi he
