### ISSUE TITLE
Pywhatkit not working

### ISSUE THREAD

**Issue by Jugatbir** [Ankit404butfound/PyWhatKit#175]
I dont know why but pywhatkit gives me an error whatever i do... i tried reinstalling as well but its not working pls help
![image_2022-01-21_160641](https://user-images.githubusercontent.com/70697551/150512641-28c02049-b560-47fb-9325-2d3ebd3d785f.png)

**Comment by Naman23-coder** [comment]
@Jugatbir `pip install flask`
and done

**Comment by Naman23-coder** [comment]
@Jugatbir this will be resolved in new pywhatkit version that will come soon

**Comment by danihuge** [comment]
great, waiting for this new version :)
Thanks!
