### ISSUE TITLE
Check complete phone number instead of just country code

### ISSUE THREAD

**Issue by nizamsalim** [Ankit404butfound/PyWhatKit#178]
Hi all,

Currently, the function to check the phone number is just checking the country code. Therefore no exception will be raised if the phone number is in an invalid format (for example : it has less than 10 digits)

I think this can be solved by checking the number with a regex expression. But since different countries have different phone number patterns, we have to take that into account too

Please let me know your thoughts

**Comment by Siddhesh-Agarwal** [comment]
We can check that using regex, like this:
```py
from re import fullmatch

regex = r"^\+?[0-9]{2,4}\s?[0-9]{10}$"
match = fullmatch.match(regex, phone_no)
```

I would suggest that we first make sure there is no space in the number. i.e `"xxxxx xxxxx"` instead of `"xxxxxxxxxx"` is wrong and should be changed to to the latter. We can do that in a simple way:
```py
phone_no = ''.join(phone_no.split())
```

**Comment by aaryanrr** [comment]
Hey @nizamsalim, thanks for the valuable suggestion. We'll include this in the next update.
@Siddhesh-Agarwal I think we can do it like this:

```py
"+910 123 456 789".replace(" ", "")
```

**Comment by Siddhesh-Agarwal** [comment]
@aaryanrr I think you are right, that seems to be a more efficient method.
