### ISSUE TITLE
Run Pyhwatkit In Background 

### ISSUE THREAD

**Issue by kue5573** [Ankit404butfound/PyWhatKit#180]
Hi Ankit,

can I set the pywhatkit run while computer is log off?

I want to use task scheduler to send  whatsapp image  with periodic time while computer is log off. 

Is that possible?

**Comment by Naman23-coder** [comment]
@kue5573 sadly, it is not possible as of now

**Comment by aaryanrr** [comment]
Hey @kue5573, thanks for reaching out. I think you will have to use a selenium based library to accomplish this.

**Comment by Manojwithcode** [comment]
File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pywhatkit/init.py"
bhai ye problem solve nahi ho rahi he
