### ISSUE TITLE
having problem importing pywhatkit

### ISSUE THREAD

**Issue by anindya127** [Ankit404butfound/PyWhatKit#181]
## Description

I was making a python ai project in my vs code. The installation of Pywhatkit was successful. But I don't know why whenever I import Pywhatkin into my program it shows this error message
"Exception ignored on calling ctypes callback function: <function catch_errors.<locals>.call_with_this at 0x000001F4DFE60280>
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\comtypes\_comobject.py", line 91, in call_with_this
  File "C:\Python310\lib\logging\__init__.py", line 1505, in error
  File "C:\Python310\lib\logging\__init__.py", line 1734, in isEnabledFor
TypeError: 'NoneType' object is not callable"
I don't know how to fix this and a search about it but didn't find any solution. I don't know if it is a bug or not can any one please help me to overcome it?

## Screenshots

![Screenshot (9)](https://user-images.githubusercontent.com/70308564/151489150-3dd8462c-2c34-4583-88ff-1a25ed65e227.png)

![Screenshot (10)](https://user-images.githubusercontent.com/70308564/151489176-57d12e67-940c-4e76-9a3c-4513103a1e5a.png)

## Version Information

- OS: [ Windows 11]
- Browser: [Microsoft Edge]
- Python: [ 3.10.2]
- PyWhatKit: [ 5.3]

**Comment by Naman23-coder** [comment]
@anindya127  `pip install pywhatkit==5.2`
try rolling back to version 5.2

**Comment by anindya127** [comment]
Ok i will try it let you know

**Comment by anindya127** [comment]
> @anindya127 `pip install pywhatkit==5.2` try rolling back to version 5.2

Thanks 🙏 it's working 😀😀

**Comment by Naman23-coder** [comment]
@anindya127 it is a common problem of logging library
