### ISSUE TITLE
Prevent new tab from opening if already open

### ISSUE THREAD

**Issue by MarcDirven** [Ankit404butfound/PyWhatKit#190]
Currently, `pywhatkit` will open a new browser tab to send a message. If however, there already is an active tab using whatsapp, it will completely ignore that one and open a new one nonetheless. Is this fixable? Would be great to see a fix for this.

**Comment by muhohokenya** [comment]
Experiencing the same issue, looking forward for a solution around it.

**Comment by aaryanrr** [comment]
Hey @MarcDirven, thanks for reaching out. Yes, a fix for this is already in progress. It will be released with the next version.

**Comment by muhohokenya** [comment]
I can't wait for this
.. Thankyou

**Comment by MarcDirven** [comment]
Great!

**Comment by BaselMahameed** [comment]
Where can I find the solution?
