### ISSUE TITLE
Clicking on the middle of the screen causes occasional unwanted side effect.

### ISSUE THREAD

**Issue by dr-noid** [Ankit404butfound/PyWhatKit#195]
## Description
I've noticed that the clicking in the center of the screen will sometimes click on the "end-to-end encryption" message.
![image](https://user-images.githubusercontent.com/67706284/156938040-0481f496-3756-47db-bb5c-9a14753597df.png)

Then this popups comes up, and the program can't continue:
![image](https://user-images.githubusercontent.com/67706284/156938138-f0df8bfc-0204-4130-8e24-a796467aabd1.png)

## Version Information

- OS: [Windows 10]
- Browser: [Google Chrome]
- Python: [3.10.2]
- PyWhatKit: [5.3]

**Comment by aaryanrr** [comment]
Hey @dr-noid, thanks for reporting this. We'll get a fix ready for it!

**Comment by rodreri** [comment]
I have the same problem, but in my case, it clicks on another group member's message (url, image), so that send fail
