### ISSUE TITLE
module 'pywhatkit' has no attribute 'playnoyt'

### ISSUE THREAD

**Issue by SAIKO9X** [Ankit404butfound/PyWhatKit#204]
## Description

I'm getting the following error when starting my program

## To Reproduce

File "c:\Users\saiko\Desktop\Jarvis\Funções\Funções.py", line 36, in <module>
    youtube("lasanha de carne")
  File "c:\Users\saiko\Desktop\Jarvis\Funções\Funções.py", line 31, in youtube
    pywhatkit.playnoyt(term)
AttributeError: module 'pywhatkit' has no attribute 'playnoyt'. Did you mean: 'playonyt'?

## Screenshots

![image](https://user-images.githubusercontent.com/95624589/162537238-b2361ed3-1ed9-4008-833b-05ef5442233d.png)

the tab __init__.py is like this:

![image](https://user-images.githubusercontent.com/95624589/162538566-85a53fb3-2770-41ee-bb0e-50012781bba9.png)

## Version Information

- OS: [e.g. Windows 10]
- Browser: [e.g. Opera Gx]
- Python: [e.g. 3.10.4]
- PyWhatKit: [e.g. 5.5]

**Comment by Naman23-coder** [comment]
@SAIKO9X it's `pywhatkit.playonyt` not playnoyt

**Comment by tdwright** [comment]
Adding to what @Naman23-coder says, the issue here is that the N and O need to be swapped. The method name (in English) can be read as Play **On** Y[ou]T[ube].

**Comment by Siddhesh-Agarwal** [comment]
Yeah, I guess this issue can be closed now?

**Comment by Ankit404butfound** [comment]
> Yeah, I guess this issue can be closed now?

Closed!
