### ISSUE TITLE
No module named 'flask'

### ISSUE THREAD

**Issue by Eltalchelo** [Ankit404butfound/PyWhatKit#206]

**Comment by Naman23-coder** [comment]
`pip install flask`

**Comment by cnshu** [comment]
you must stop coding @Eltalchelo

**Comment by IGI-Research-Devs** [comment]
> you must stop coding @Eltalchelo

why because a package which was suppose to be pre-installed wasnt there? i also installed on my own with pip but it should be mentioned that its not part of project then.

**Comment by SigireddyBalasai** [comment]
Bro flask can be installed and is not related to here
