### ISSUE TITLE
Make time.sleep async

### ISSUE THREAD

**Issue by MarcDirven** [Ankit404butfound/PyWhatKit#228]
## Related Problem

Currently, all `sleep` are synchronous, it'd be better to change it to `async` code.

## Feature Description

Change all synchronous `time.sleep` to `await asyncio.sleep`.

**Comment by SigireddyBalasai** [comment]
But there are something we need to consider bro it will be a coroutine i will be good to do a seperate asynchronous branch and is being planned in upcoming updates

**Comment by MarcDirven** [comment]
Sure thing 👍🏼

**Comment by SigireddyBalasai** [comment]
You can check this https://github.com/SigireddyBalasai/AsyncPywhatKit 
Bye
