### ISSUE TITLE
Is there a way one could send ONE message to MANY numbers?

### ISSUE THREAD

**Issue by JoelSmalls** [Ankit404butfound/PyWhatKit#234]
I have been researching ways and means of having one message being sent to all users in a given list. The problem is, though, that when using a list with numbers and looping through them, it immediately fires up all three instances and sends message to only one of them. When adding "sleep", it only fires up one instance and then says "sucessful" even though it only sent a message to one out of two people.

```
# importing the module
import pywhatkit
import datetime
import time

nums = ["+1234","+5678"]

try:

        for c in nums:
                pywhatkit.sendwhatmsg(c, "Testing Automatic Whatsapp",xHour, yMinute, 20)
                print("Successfully Sent!")
                time.sleep(25)

except:
  print("An Unexpected Error!")

```

Therefore is there a way at all to send a message to multiple people?

**Comment by camiloricoe** [comment]
Hey Joel, you can use this method instead, sendwhatsmsg_to_all, it accepts a list of the phones

def sendwhatsmsg_to_all(
    phone_nos: List[str], etc...
