### ISSUE TITLE
Steps missing in Documention when Building from source

### ISSUE THREAD

**Issue by akankshasainics** [Ankit404butfound/PyWhatKit#236]
## Description

In the [documentation](https://github.com/Ankit404butfound/PyWhatKit/wiki#building-from-source), following steps are missing.

- After **Step1** in documentation (cloning the repository), the next step should be changing the directory ( `cd PyWhatKit`), otherwise **Step3** (installing the requirements) will give an error. 
-  we need to activate the virtual environment after creation, on Linux (
`source venv/bin/activate`)

**Comment by Ankit404butfound** [comment]
Updated!
