### ISSUE TITLE
ImportError: cannot import name 'web_screenshot' from 'pywhatkit.misc'

### ISSUE THREAD

**Issue by FabinhoSchramm** [Ankit404butfound/PyWhatKit#237]
## Description

ImportError: cannot import name 'web_screenshot' from 'pywhatkit.misc'

## Screenshots

![image](https://user-images.githubusercontent.com/110568802/194933813-e0c5c385-7987-444d-9685-3402287a9ea9.png)

## Version Information

- OS: [Windows 10]
- Browser: [Google Chrome]
- Python: [3.10.6]
- PyWhatKit: [5.3]

**Comment by FabinhoSchramm** [comment]
error solved in version 5.4

**Comment by Naman23-coder** [comment]
@FabinhoSchramm `web_screenshot` has been removed
