### ISSUE TITLE
Text To Handwriting Unable to access Pywhatkit api right now

### ISSUE THREAD

**Issue by svmalvaez** [Ankit404butfound/PyWhatKit#249]
## Description

When using pywhatkit.text_to_handwriting(text) get an exception:

UnableToAccessApi: Unable to access Pywhatkit api right now

## To Reproduce

import pywhatkit
text='your text' 
pywhatkit.text_to_handwriting(text)

## Screenshots

<img width="614" alt="Captura de Pantalla 2022-12-16 a la(s) 14 09 08" src="https://user-images.githubusercontent.com/5864643/208180972-060aee47-db20-48b6-b8cd-50dc36879c24.png">
<img width="774" alt="Captura de Pantalla 2022-12-16 a la(s) 14 08 44" src="https://user-images.githubusercontent.com/5864643/208180977-fd3baf64-8653-4794-8fea-f162320ed2fd.png">

If applicable, add Screenshots to help explain your Problem

## Version Information

- OS: MacOS
- Browser: Google Chrome
- Python: 3.10.1
- PyWhatKit: 5.3

You can Check the PyWhatKit Version using

```py
print(pywhatkit.__VERSION__)
```

**Comment by Ankit404butfound** [comment]
![image](https://user-images.githubusercontent.com/54436840/208285498-2adaba95-8483-4433-92d3-74f6eb72d55c.png)
As Heroku will no longer support free dyno, this feature will be available after some time once we set up the server somewhere else.

**Comment by IgorMunizS** [comment]
Isn't this feature open-source? Where can I get the source code instead of an API request?

**Comment by Ankit404butfound** [comment]
> Isn't this feature open-source? Where can I get the source code instead of an API request?

Source code can be found here https://github.com/Ankit404butfound/pywhatkit.herokuapp.com/blob/3025a13b6782e62689d3066bcd3cfc4276c07de3/app.py#L133.
