### ISSUE TITLE
module 'os' has no attribute 'startfile'

### ISSUE THREAD

**Issue by TheShubhendra** [Ankit404butfound/PyWhatKit#26]
Operating system : **Android 8.1.0**
Environment : **Termux**

```bash
>>> text = "Hello world"
>>> pywhatkit.text_to_handwriting(text,rgb=[0,0,0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pywhatkit/chr_to_handwriting.py", line 9, in text_to_handwriting
    os.startfile(save_to)
AttributeError: module 'os' has no attribute 'startfile'
```

**Comment by aaryanrr** [comment]
What is the python version you are using?

**Comment by TheShubhendra** [comment]
> What is the python version you are using?

**python 3.9.0**

**Comment by aaryanrr** [comment]
I think this won't work in termux beacause it is a command line utility and os.startfile() would require a GUI interface to open a new window with the text file opened in it. Other than this try installing python with termux on another device and see if the issue continues.

**Comment by aaryanrr** [comment]
@TheShubhendra Please close this issue if it is resolved or of no use now. 🙂

**Comment by TheShubhendra** [comment]
<blockquote
cute="https://docs.python.org/3/library/os.html#os.startfile">
os.startfile(path[, operation])

Start a file with its associated application.
..........

Availability: Windows
</blockquote>

**Source:** https://docs.python.org/3/library/os.html#os.startfile

This property is only available for Windows

**Comment by aaryanrr** [comment]
Oh i see!!

**Comment by yogesh-7** [comment]
it is a windows only command if you are using this on ubuntu i will not work

**Comment by Akash-nath29** [comment]
Then what should I use for android ?

**Comment by Naman23-coder** [comment]
@Akash-nath29 i don't think it will work on android

**Comment by Akash-nath29** [comment]
Ok 😕

**Comment by deandegil** [comment]
for mac Os : u can run startfile e.g:

def startfile(fn):
os.system('open %s' % fn)
