### ISSUE TITLE
when i use the pywhatkit in flask, the server stopworking... 

### ISSUE THREAD

**Issue by Rasantis** [Ankit404butfound/PyWhatKit#261]
im using the latest stable version, it would be great fixing it.

**Comment by Ankit404butfound** [comment]
All the functions of PyWhatKit are blocking, meaning, until the function has not completely executed, it will stop any parent loop.
I'm order to work around this, consider using threading module along with PyWhatKit.

**Comment by SigireddyBalasai** [comment]
I think you can also use AsyncPywhatKit
