### ISSUE TITLE
Misspelled Function Description

### ISSUE THREAD

**Issue by aaryanrr** [Ankit404butfound/PyWhatKit#27]
The function image_to_ascii_art() is having a misspelled description when i installed the module but when i saw that same file here on the repository it was spelled correctly. The file where this function is declared is having this misspelled description.

1. Install pywhatkit in a virtual environment. (I haven't tested it )
2. Create a python file and import pywhatkit.
3. Access the image_to_ascii_art() function and hover over it to see the description.

**Expected behavior**
The function description says `Converts the given image to ascii art and save it to uotput_file` but it should be correctly spelled as it is given in the repository.

**Screenshots**

![Screenshot (28)](https://user-images.githubusercontent.com/73213670/103462726-4af01280-4d4d-11eb-9bfd-571eabca0549.png)

![Screenshot (29)](https://user-images.githubusercontent.com/73213670/103462839-0a44c900-4d4e-11eb-8986-02cec9563ae3.png)

**Desktop **
 - OS: Windows 10 Version 1909
 - Browser: Microsoft Edge
 - Version: 87.0.664.

**Python Related Details**
Version: 3.9.1
Pip Version: 20.3.3

**Additional context**
I know that this isn't anything related to any error but I want to know why is this happening and is it happening to me only or someone else too.

**Comment by TheShubhendra** [comment]
This typo has been corrected in 8afd3550b6d51f4d91e0d1e82bc01d8aee13ab3b and will update on pypi packages with the next release

**Comment by aaryanrr** [comment]
Thanks for the update!
