### ISSUE TITLE
Emojis in sendwhatmsg_to_group don't appear in message

### ISSUE THREAD

**Issue by Aurreko17** [Ankit404butfound/PyWhatKit#274]
Hello! I want to send this message in WhatsApp groups: "Python Test 💪💪💪"

When I send it with sendwhatmsg_instantly it outputs what is intended in WhatsApp, but when I use sendwhatmsg_to_group or sendwhatmsg_to_group_instantly, it only outputs "Python Test".

I have tested using \U0001F4AA instead of emojis and it works in sendwhatmsg_instantly but not in groups, also I tried using the emoji library, but nothing. 

Another thing that worked was using :flex and then adding the function press from the pyautogui library, and it works, but I can only inputs one emoji. 

Is there a way to make this work, or a bug fix is needed?

**This is my code:**

import pywhatkit as kit

wait_time = 10
string = "Python Test \U0001F4AA\U0001F4AA\U0001F4AA"

kit.sendwhatmsg_to_group_instantly("group_code",  string, wait_time)

_OR_

import pywhatkit as kit
from pyautogui import press

wait_time = 10
string = "Python Test :flex :flex :flex"

kit.sendwhatmsg_to_group_instantly("group_code",  string, wait_time)
press("enter")

**Version Information**

PyWhatKit  Version 5.3 (Stable)

**Comment by ashurffw** [comment]
Don't need this pres("enter"), the bot also have this function. Put the emoji in your code like this 
![image](https://user-images.githubusercontent.com/103474624/235327761-2b5759ef-dbc8-470c-9b7b-c7a03b113e0a.png)

**Comment by ashurffw** [comment]
![image](https://user-images.githubusercontent.com/103474624/235327793-2ba01c5a-4b2c-4f04-a26e-2ae10c399228.png)
Bro, don't need this press("enter"), the bot also have this function. Put the emoji at the code like that

**Comment by Aurreko17** [comment]
This is the output with your code:

![imagen](https://user-images.githubusercontent.com/126499602/235356327-77c21f35-93b7-4a7e-9b48-8a4a536dfa56.png)


![imagen](https://user-images.githubusercontent.com/126499602/235356078-b37ad93d-bec2-4672-b135-a602799510f7.png)

It's the issue I was telling you about on the previous comment

**Comment by Vashesh08** [comment]
@Ankit404butfound I have attempted to solve this issue. Please review the PR #299
