### ISSUE TITLE
shutdown is not recognized as a external or internal command

### ISSUE THREAD

**Issue by AnkitMitraOfficial** [Ankit404butfound/PyWhatKit#28]
whenever I try to do -- 
pywhatkit.shutdown(time=10)#any time
I get the error -- shutdown is not recognized as a external or internal command

Anyone with the same error?

Can anyone help me with this how to fix it, is the problem with the module or my computer?
I am using windows 7 32 bit, python I am using - 3.8.6

**Comment by Ankit404butfound** [comment]
Can you please mention the OS you are working on.

**Comment by aaryanrr** [comment]
Can you try to run the shutdown -s command in your command prompt and tell if it worked

**Comment by AnkitMitraOfficial** [comment]
> Can you please mention the OS you are working on.

windows 7, 32 bit

**Comment by AnkitMitraOfficial** [comment]
> Can you try to run the shutdown -s command in your command prompt and tell if it worked

nope. didn't worked!

**Comment by aaryanrr** [comment]
Then it is a problem with your system. Shutdown is an external command i.e., it has its own executable in C:\Windows\System32 and if the path variables are not correctly configured or the executable is missing it may result in this error. See [this](https://superuser.com/questions/670850/commands-not-working-in-windows-7-32-bit-command-prompt) for help. If it does not resolve the issue try contacting Microsoft Support.

**Comment by Ankit404butfound** [comment]
@aaryanrr is right, I think shutdown.exe is not in your path.
