### ISSUE TITLE
Message Sending not working

### ISSUE THREAD

**Issue by veresh** [Ankit404butfound/PyWhatKit#310]
For the last few days, message sending stopped working 
Using MacOS Ventura
Python 3.8.2
## To Reproduce

The following is not working 
pywhatkit.sendwhatmsg_instantly("+91XXXXXXX", "hello", 15)
pywhatkit.sendwhatmsg_to_group_instantly("XXXX", "Hey All!")

 It was working fine earlier so not sure its the OS issue or the chrome issue or the utility issue

You can Check the PyWhatKit Version using
Using Pywhatkit 5.4

**Comment by basb7** [comment]
Recently I have the equal problem. I solved added this line in file core the la lib pywhatkit.

`def send_message(message: str, receiver: str, wait_time: int) -> None:
    """Parses and Sends the Message"""

    _web(receiver=receiver, message=message)
    time.sleep(7)
    click(WIDTH / 2, HEIGHT / 2)
    time.sleep(wait_time - 7)
    if not check_number(number=receiver):
        for char in message:
            if char == "\n":
                hotkey("shift", "enter")
            else:
                typewrite(char)
    time.sleep(5) 
    press("enter")`

**Comment by viditpandey06** [comment]
@veresh The recent update has fixed this issue.
