### ISSUE TITLE
Write the message but don't send it

### ISSUE THREAD

**Issue by marcosdsdba** [Ankit404butfound/PyWhatKit#314]
Write the message but don't send it

When a try sendwhatmsg, open chromium, open webwhatsapp, he types the message, 
but pywhatkit not sending a message.

## Version Information
- OS: Raspbian OS 64bit - Debian 12 (64-bit) (bookworm)
- Browser: Chromium Version 120.0.60.99.102. - Debian 12 (64-bit)
- Python: 3.11.2
- PyWhatKit: 5.3 stable

**Comment by AlishaB21** [comment]
Having the same issue

**Comment by egbertomonteiro** [comment]
same issue.

**Comment by programmer262** [comment]
**### The same**

**Comment by GuiAs1** [comment]
I was with this problem, but i use the library "Keyboard" and after the line " pywhatkit.sendwhatmsg" i used "keyboard.press_and_release('enter')" and worth it

**Comment by marcosdsdba** [comment]
Try downgrade python to 3.6
Works fine for me.

**Comment by arjunapanji21** [comment]
I try to change the delay between click and enter in whats.py and run the program.. it fix the issue.

[Before]
![image](https://github.com/Ankit404butfound/PyWhatKit/assets/75791180/777136be-049f-4a46-a8b7-04a0d47272f6)


[After]
![image](https://github.com/Ankit404butfound/PyWhatKit/assets/75791180/fdad5103-8633-487e-95c0-76fad9b46465)

**Comment by Jordan-05-max** [comment]
The web page is initialized successfully, and the message is written but not sent.
The image is loaded but not sent also

**Comment by r3po-1s-Tr3e** [comment]
The following can be tried too: (just using the keyboard library didnt work for me)

import pywhatkit
import keyboard
import time
import pyautogui

pywhatkit.sendwhatmsg("Number", "Change of text")
pyautogui.click()
keyboard.press_and_release('enter')

**Comment by viditpandey06** [comment]
This issue has been resolved in the latest update.
