### ISSUE TITLE
Messages are displayed on window but not send until done manually..

### ISSUE THREAD

**Issue by viditpandey06** [Ankit404butfound/PyWhatKit#322]
## Description

While using the tool the message are typed in the text box but the send key is not pressed automatically.
## To Reproduce

Steps to Reproduce the Bug
Start the program and use the command to send message.
# Send the message
    pwk.sendwhatmsg(formatted_number, 'message', hr, min) # Change the message as per your requirement

## Version Information

- OS:  Windows 11
- Browser:  Microsoft Edge, Google Chrome
- Python: 3.11
- PyWhatKit: 5.2

**Comment by ziyad00** [comment]
same
