### ISSUE TITLE
Can't install on Windows

### ISSUE THREAD

**Issue by Moosbueffel** [Ankit404butfound/PyWhatKit#37]
I use PhyCharm going to the terminal. There I put your 

`pip install pywhatkit
`
and I use:

```
(venv) C:\Users\sch\PycharmProjects\WhatsAppMsg>python --version
Python 3.8.2

(venv) C:\Users\sch\PycharmProjects\WhatsAppMsg>pip --version
pip 19.0.3 from C:\Users\Schorsch\PycharmProjects\WhatsAppMsg\venv\lib\site-packages\pip-19.0.3-py3.8.egg\pip (python 3.8)

```

The output is than:

`(venv) C:\Users\sch\PycharmProjects\WhatsAppMsg>pip install pywhatkit
Collecting pywhatkit
  Using cached https://files.pythonhosted.org/packages/2f/bf/6b9a6d676d526156ca7639ec61b1202d1192b4e4d806639aec507a66546e/pywhatkit-3.9-py3-none-any.whl
Collecting pyautogui (from pywhatkit)
  Using cached https://files.pythonhosted.org/packages/40/0a/1373680148828d7ea3f0e432f06c08f51a33d72306719954d3ae379f5890/PyAutoGUI-0.9.52.tar.gz
Requirement already satisfied: requests in c:\users\sch\pycharmprojects\whatsappmsg\venv\lib\site-packages (from pywhatkit) (2.25.1)
Collecting Pillow (from pywhatkit)
  Using cached https://files.pythonhosted.org/packages/73/59/3192bb3bc554ccbd678bdb32993928cb566dccf32f65dac65ac7e89eb311/Pillow-8.1.0.tar.gz
Requirement already satisfied: wikipedia in c:\users\sch\pycharmprojects\whatsappmsg\venv\lib\site-packages (from pywhatkit) (1.4.0)
Requirement already satisfied: beautifulsoup4 in c:\users\sch\pycharmprojects\whatsappmsg\venv\lib\site-packages (from pywhatkit) (4.9.3)
Collecting pymsgbox (from pyautogui->pywhatkit)
Collecting PyTweening>=1.0.1 (from pyautogui->pywhatkit)
  Using cached https://files.pythonhosted.org/packages/b9/f8/c32a58d6e4dff8aa5c27e907194d69f3b57e525c2e4af96f39c6e9c854d2/PyTweening-1.0.3.zip
Collecting pyscreeze>=0.1.21 (from pyautogui->pywhatkit)
  Using cached https://files.pythonhosted.org/packages/b7/7d/a0e85da28a96e2ff2f39e682ff84eb92501b564883fde87d92aee29966a2/PyScreeze-0.1.26.tar.gz
Collecting pygetwindow>=0.0.5 (from pyautogui->pywhatkit)
  Using cached https://files.pythonhosted.org/packages/e1/70/c7a4f46dbf06048c6d57d9489b8e0f9c4c3d36b7479f03c5ca97eaa2541d/PyGetWindow-0.0.9.tar.gz
Collecting mouseinfo (from pyautogui->pywhatkit)
  Using cached https://files.pythonhosted.org/packages/28/fa/b2ba8229b9381e8f6381c1dcae6f4159a7f72349e414ed19cfbbd1817173/MouseInfo-0.1.3.tar.gz
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sch\pycharmprojects\whatsappmsg\venv\lib\site-packages (from requests->pywhatkit) (2020.12.5)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\sch\pycharmprojects\whatsappmsg\venv\lib\site-packages (from requests->pywhatkit) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in c:\users\sch\pycharmprojects\whatsappmsg\venv\lib\site-packages (from requests->pywhatkit) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\sch\pycharmprojects\whatsappmsg\venv\lib\site-packages (from requests->pywhatkit) (1.26.2)
Requirement already satisfied: soupsieve>1.2; python_version >= "3.0" in c:\users\sch\pycharmprojects\whatsappmsg\venv\lib\site-packages (from beautifulsoup4->pywhatkit) (2.1)
Collecting pyrect (from pygetwindow>=0.0.5->pyautogui->pywhatkit)
  Using cached https://files.pythonhosted.org/packages/2f/68/bd7bf96fc44217e769f27912e6c9bb3e9987cba286054af6120448ce8212/PyRect-0.1.4.tar.gz
Collecting pyperclip (from mouseinfo->pyautogui->pywhatkit)
  Using cached https://files.pythonhosted.org/packages/6f/4c/0b1d507ad7e8bc31d690d04b4f475e74c2002d060f7994ce8c09612df707/pyperclip-1.8.1.tar.gz
Installing collected packages: pymsgbox, PyTweening, Pillow, pyscreeze, pyrect, pygetwindow, pyperclip, mouseinfo, pyautogui, pywhatkit
  Running setup.py install for PyTweening ... done
  Running setup.py install for Pillow ... error
    Complete output from command C:\Users\sch\PycharmProjects\WhatsAppMsg\venv\Scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\sch\\AppData\\Local\\Temp\\p
ip-install-t7cjrtb6\\Pillow\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\User
s\sch\AppData\Local\Temp\pip-record-rts0lbgx\install-record.txt --single-version-externally-managed --compile --install-headers C:\Users\sch\PycharmProjects\WhatsAppMsg\venv\include\
site\python3.8\Pillow:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.8
    creating build\lib.win32-3.8\PIL
    copying src\PIL\BdfFontFile.py -> build\lib.win32-3.8\PIL
    copying src\PIL\BlpImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\BmpImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\BufrStubImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\ContainerIO.py -> build\lib.win32-3.8\PIL
    copying src\PIL\CurImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\DcxImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\DdsImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\EpsImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\ExifTags.py -> build\lib.win32-3.8\PIL
    copying src\PIL\features.py -> build\lib.win32-3.8\PIL
    copying src\PIL\FitsStubImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\FliImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\FontFile.py -> build\lib.win32-3.8\PIL
    copying src\PIL\FpxImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\FtexImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\GbrImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\GdImageFile.py -> build\lib.win32-3.8\PIL
    copying src\PIL\GifImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\GimpGradientFile.py -> build\lib.win32-3.8\PIL
    copying src\PIL\GimpPaletteFile.py -> build\lib.win32-3.8\PIL
    copying src\PIL\GribStubImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\Hdf5StubImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\IcnsImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\IcoImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\Image.py -> build\lib.win32-3.8\PIL
    copying src\PIL\ImageChops.py -> build\lib.win32-3.8\PIL
    copying src\PIL\ImageCms.py -> build\lib.win32-3.8\PIL
    copying src\PIL\ImageColor.py -> build\lib.win32-3.8\PIL
    copying src\PIL\ImageDraw.py -> build\lib.win32-3.8\PIL
    copying src\PIL\ImageDraw2.py -> build\lib.win32-3.8\PIL
    copying src\PIL\ImageEnhance.py -> build\lib.win32-3.8\PIL
    copying src\PIL\ImageFile.py -> build\lib.win32-3.8\PIL
    copying src\PIL\ImageFilter.py -> build\lib.win32-3.8\PIL
    copying src\PIL\ImageFont.py -> build\lib.win32-3.8\PIL
    copying src\PIL\ImageGrab.py -> build\lib.win32-3.8\PIL
    copying src\PIL\ImageMath.py -> build\lib.win32-3.8\PIL
    copying src\PIL\ImageMode.py -> build\lib.win32-3.8\PIL
    copying src\PIL\ImageMorph.py -> build\lib.win32-3.8\PIL
    copying src\PIL\ImageOps.py -> build\lib.win32-3.8\PIL
    copying src\PIL\ImagePalette.py -> build\lib.win32-3.8\PIL
    copying src\PIL\ImagePath.py -> build\lib.win32-3.8\PIL
    copying src\PIL\ImageQt.py -> build\lib.win32-3.8\PIL
    copying src\PIL\ImageSequence.py -> build\lib.win32-3.8\PIL
    copying src\PIL\ImageShow.py -> build\lib.win32-3.8\PIL
    copying src\PIL\ImageStat.py -> build\lib.win32-3.8\PIL
    copying src\PIL\ImageTk.py -> build\lib.win32-3.8\PIL
    copying src\PIL\ImageTransform.py -> build\lib.win32-3.8\PIL
    copying src\PIL\ImageWin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\ImImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\ImtImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\IptcImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\Jpeg2KImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\JpegImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\JpegPresets.py -> build\lib.win32-3.8\PIL
    copying src\PIL\McIdasImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\MicImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\MpegImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\MpoImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\MspImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\PaletteFile.py -> build\lib.win32-3.8\PIL
    copying src\PIL\PalmImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\PcdImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\PcfFontFile.py -> build\lib.win32-3.8\PIL
    copying src\PIL\PcxImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\PdfImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\PdfParser.py -> build\lib.win32-3.8\PIL
    copying src\PIL\PixarImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\PngImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\PpmImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\PsdImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\PSDraw.py -> build\lib.win32-3.8\PIL
    copying src\PIL\PyAccess.py -> build\lib.win32-3.8\PIL
    copying src\PIL\SgiImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\SpiderImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\SunImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\TarIO.py -> build\lib.win32-3.8\PIL
    copying src\PIL\TgaImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\TiffImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\TiffTags.py -> build\lib.win32-3.8\PIL
    copying src\PIL\WalImageFile.py -> build\lib.win32-3.8\PIL
    copying src\PIL\WebPImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\WmfImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\XbmImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\XpmImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\XVThumbImagePlugin.py -> build\lib.win32-3.8\PIL
    copying src\PIL\_binary.py -> build\lib.win32-3.8\PIL
    copying src\PIL\_tkinter_finder.py -> build\lib.win32-3.8\PIL
    copying src\PIL\_util.py -> build\lib.win32-3.8\PIL
    copying src\PIL\_version.py -> build\lib.win32-3.8\PIL
    copying src\PIL\__init__.py -> build\lib.win32-3.8\PIL
    copying src\PIL\__main__.py -> build\lib.win32-3.8\PIL
    running egg_info
    writing src\Pillow.egg-info\PKG-INFO
    writing dependency_links to src\Pillow.egg-info\dependency_links.txt
    writing top-level names to src\Pillow.egg-info\top_level.txt
    reading manifest file 'src\Pillow.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.c'
    warning: no files found matching '*.h'
    warning: no files found matching '*.sh'
    warning: no previously-included files found matching '.appveyor.yml'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.readthedocs.yml'
    warning: no previously-included files found matching 'codecov.yml'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    no previously-included directories found matching '.ci'
    writing manifest file 'src\Pillow.egg-info\SOURCES.txt'
    running build_ext

    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html

    Traceback (most recent call last):
      File "C:\Users\sch\AppData\Local\Temp\pip-install-t7cjrtb6\Pillow\setup.py", line 865, in <module>
        setup(
      File "C:\Users\sch\PycharmProjects\WhatsAppMsg\venv\lib\site-packages\setuptools-40.8.0-py3.8.egg\setuptools\__init__.py", line 145, in setup
      File "C:\Programme (USB)\Python\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Programme (USB)\Python\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Programme (USB)\Python\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\sch\PycharmProjects\WhatsAppMsg\venv\lib\site-packages\setuptools-40.8.0-py3.8.egg\setuptools\command\install.py", line 61, in run
      File "C:\Programme (USB)\Python\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\Programme (USB)\Python\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Programme (USB)\Python\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Programme (USB)\Python\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Programme (USB)\Python\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Programme (USB)\Python\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\sch\PycharmProjects\WhatsAppMsg\venv\lib\site-packages\setuptools-40.8.0-py3.8.egg\setuptools\command\build_ext.py", line 78, in run
      File "C:\Programme (USB)\Python\lib\distutils\command\build_ext.py", line 340, in run
        self.build_extensions()
      File "C:\Users\sch\AppData\Local\Temp\pip-install-t7cjrtb6\Pillow\setup.py", line 702, in build_extensions
        raise RequiredDependencyException(f)
    __main__.RequiredDependencyException: zlib

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\sch\AppData\Local\Temp\pip-install-t7cjrtb6\Pillow\setup.py", line 922, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:

    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html

    ----------------------------------------
Command "C:\Users\sch\PycharmProjects\WhatsAppMsg\venv\Scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\sch\\AppData\\Local\\Temp\\pip-install-t7cjrtb6\\Pil
low\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\sch\AppData\Local
\Temp\pip-record-rts0lbgx\install-record.txt --single-version-externally-managed --compile --install-headers C:\Users\sch\PycharmProjects\WhatsAppMsg\venv\include\site\python3.8\Pillow" f
ailed with error code 1 in C:\Users\sch\AppData\Local\Temp\pip-install-t7cjrtb6\Pillow\

`

**Comment by Ankit404butfound** [comment]
Hi, this is issue with the pillow library, please try `pip install pywhatkit==2.2 ` or `pip install pywhatkit==3.9`
Either one should work.

**Comment by Moosbueffel** [comment]
Installation now works installing from powerShell.
Also it works on windows. I wanted to us ist on a Raspi. There is no browser installed and no whatsapp web (scanned QR code). So it will not work there??
Installing an browser und scanning QR code is also not a solution, because, I use whatsapp we on my pc. And I can only use one PC - right

**Comment by aaryanrr** [comment]
Hey @Moosbueffel 
If you are using a Raspberry Pi and running a Linux distribution or Windows in it, you can install a browser and python3 in it and as WhatsApp web works in any browser it should work there also, [See this](https://pimylifeup.com/raspberry-pi-chromium-browser/). Also, you can use WhatsApp web on multiple devices. For Ex: Windows has a dedicated App on [Microsoft Store](https://www.microsoft.com/en-us/p/whatsapp-desktop/9nksqgp7f2nh?activetab=pivot:overviewtab) for WhatsApp which has a persistent login unlike the web version. You can use both the app and another web session on the same or any other device simultaneously. As far as it goes with scanning the QR Code, you need to have WhatsApp app on a device to use WhatsApp web. I don't why it's like that but this is the only way.

**Comment by Moosbueffel** [comment]
Thanks @aaryanrr I have to try, but I'm not sure, if I wrote my question/problem excactly.
- I have a raspi without a GUI. I use it only headless (as a server) via SSH. So I think I can't install a browser!?
- Because of this my fear ist, that I can't get the QR-code on my Raspi to scan with the WhatsApp App!? And as I remember this is essential to use Whatsapp web!?

**Comment by aaryanrr** [comment]
If you are using it via SSH then you can't. One thing that you can do is to install xrdp (Remote Desktop Protocol) and other GUI essentials from the terminal and use Windows Remote Desktop Connection to connect to you raspi using over RDP.


See [this](https://linuxize.com/post/how-to-install-xrdp-on-raspberry-pi/)

**Comment by kalyan70** [comment]
OSError: [Errno 9] Bad file descriptor
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.



what i do ?
![Screenshot (557)](https://user-images.githubusercontent.com/69498206/209346512-6f3287e4-4295-421b-8533-45c6e0e9140a.png)

**Comment by ns23k** [comment]
@kalyan70 pls open a new issue on this

**Comment by Ankit404butfound** [comment]
> OSError: [Errno 9] Bad file descriptor [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> See above for output.
> 
> what i do ? ![Screenshot (557)](https://user-images.githubusercontent.com/69498206/209346512-6f3287e4-4295-421b-8533-45c6e0e9140a.png)
Likely an issue with Python version, try Python version 3.9 or below.

**Comment by maybeitsai** [comment]
![image](https://github.com/Ankit404butfound/PyWhatKit/assets/130530985/dfe0b85a-95c9-48ec-be12-9457cbddc9ff)
how to fix this?
