### ISSUE TITLE
NO INTERNET - Pywhatkit needs active internet connection

### ISSUE THREAD

**Issue by obinakiller** [Ankit404butfound/PyWhatKit#38]
Hello,

I am having problems using PyWhatKit on a Desktop that works on a proxy.
The message always appears, whatever the script used: 

"ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1124)"
"urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1124)')))"
"pywhatkit.mainfunctions.InternetException: NO INTERNET - Pywhatkit needs active internet connection"

How can I resolve this issue? The desktop works in a proxy, but has free access to the internet.

Thank you.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser Chrome
 - Version 88.0.4324.146

**Comment by Ankit404butfound** [comment]
This is raised when the code fails to connect with google.com, make sure your firewall and proxy isn't blocking the code.

**Comment by hauj12123** [comment]
> This is raised when the code fails to connect with google.com, make sure your firewall and proxy isn't blocking the code.

It looks like the issue of verify of SSL certification, not connection problem. I double check with the port and ping with sites and work. Also, "Max retries exceeded with url" probably points to too many retrieval and being blocked as a result. Is it possible?!

**Comment by aaryanrr** [comment]
The `ssl.SSLError: [SSL: WRONG_VERSION_NUMBER]` error occurs if using a depreciated version of `TLS` protocol while trying to Establish a secure connection. For the `urllib3.exceptions.MaxRetryError` , it occurs when the website can't be reached after a certain number of tries. A website blocking a client may happen but is less common. 

See [this](https://urllib3.readthedocs.io/en/latest/reference/urllib3.exceptions.html).
