### ISSUE TITLE
PyWhatKit creating issue with Tkinter

### ISSUE THREAD

**Issue by AmulyaParitosh** [Ankit404butfound/PyWhatKit#41]
**Describe the bug**
I am making a virtual assistant and using PyWhatKit for playing youtube videos. I am also usinng Tkinter for GUI interaction with my assistant. When I import my GUI and PyWhatKit modules, the the GUI window reduces in size (something like 30% reduction in total size). I have checker multiple times by commenting out each moude one by one and its 'import pywhatkit' which is causing problem. I am also using threading to run GUI and local server.
My GUI is in server. When server is opened seperatly and the client is connected after wards there is no issue, but when trying to open two scripts (GUI-server and main assistant script) by importing them togeather in third script, the problem presents itself.

**To Reproduce**
I am unable to reproduce it in simple way.

This is expected outcome----
![Screenshot (4)](https://user-images.githubusercontent.com/76733670/107852042-40d52f80-6e34-11eb-867b-e2b67285061d.png)

This is what happens after PyWhatKit imports----
![Screenshot (5)](https://user-images.githubusercontent.com/76733670/107852074-8b56ac00-6e34-11eb-9ad3-d08ebefae56d.png)

**Desktop (please complete the following information):**
 - OS: [windows10]
 - Browser [chrome]
 - Version [88.0.4324.150]

**Comment by aaryanrr** [comment]
Hey @AmulyaParitosh , It would be easier to resolve the issue if you can please provide more information on this, like what other libraries are you using, python version etc.

**Comment by AmulyaParitosh** [comment]
I am using many libraries-

socket
threading
tkinter
json
pydictionary
speech_recodnition
pynewsapi
datetime
wikipedia
webbrowser
pyjokes
wolframalpha
random
pickle
numpy
nltk
tensorflow.keras.modles
pyttsx3
requests
and PyWhatKit

these are all that i am using

**Comment by aaryanrr** [comment]
I think the file chr_to_handwriting.py is messing with the screen size because of the globally declared [height and width](https://github.com/Ankit404butfound/PyWhatKit/blob/3a3df0ded0889b79ec6622792aaa7a6521e6928b/pywhatkit/chr_to_handwriting.py#L16) variable's in it. Try to debug your code by setting a breakpoint at the line where PyWhatKit is loaded.

**Comment by AmulyaParitosh** [comment]
No luck!
Same thing happned.  What is chr_to_handwriting.py ?

**Comment by aaryanrr** [comment]
It stands for Character to Handwriting and allows you to get written text images of characters that you want. See the README.md for reference. If you don't want all the functions of this library then just copy the function code you want and paste it in your own script to use it from. Till then I'll take a look into what's causing this.

**Comment by AmulyaParitosh** [comment]
I looked into chr_to_handwriting.py bt was unable to understand what to do and what functions I specifically.
Thanku for looking into it.
Hopefully @Ankit404butfound can help me.

**Comment by Ankit404butfound** [comment]
I think it has to do with environmental variables, although I am not using any environmental variable but I am very sure that some inner packages are changing it. You need to verify which variable is changing and then you could redefine the variable after importing the package.
Something like this

```
import os
import pywhatkit

os.environ["Var-Name"] = "Expected-var-value"
```

**Comment by AmulyaParitosh** [comment]
I checked the environment variables using print(os.environ) printing before importing PyWhatKit then after importing PyWhatKit and compaired but found no difference b/w both.

![Screenshot (7)](https://user-images.githubusercontent.com/76733670/107869850-b2ef5800-6eb8-11eb-92ae-df715ed7d7dc.png)

**Comment by AmulyaParitosh** [comment]
I use the required function from mainfunctions.py  in PyWhatKit and now it's working flawlessly. Thanku

**Comment by lcampos777** [comment]
Hello, I'm some wheat new with Python and have the same issue described above, I'm unable to make that my GUI doesn't change the layout even after using just the code for the "sendwhatmsg_instantly" function in my own script, will appreciate if you can provide some guidance. Thank you.

**Comment by aaryanrr** [comment]
Hey @lcampos777 , If you are directly using the code of that function you will have these lines in it,
```py
width, height = pg.size()
pg.click(width / 2, height / 2)
```
Remove these and try again

**Comment by lcampos777** [comment]
@aaryanrr Thanks for the prompt response, already tried what you mentioned (did not remove the lines, instead just commented both) but unfortunately the issue remains. I'm adding a screenshot of how the code looks like to see if maybe by looking at it you can identify if I'm doing something wrong. Again, thanks for looking into this


![carbon (2)](https://user-images.githubusercontent.com/87612724/126074827-ef8424b7-d611-4b69-aae9-31d7c9d40a4a.png)

**Comment by lcampos777** [comment]
Wanted to mention that for the functions showing in the above screenshot to function I had to do some imports (see below screenshot), after testing one by one the line `import pyautogui as pg` seems to be the one causing that the layout in the GUI changes. 

![carbon (1)](https://user-images.githubusercontent.com/87612724/126075013-4f65f7e3-d68b-406f-9520-9c2a126ac6e0.png)

**Comment by aaryanrr** [comment]
Can you try to import only the required functions from `pyautogui` like 
```py
from pyautogui import press, hotkey
```
and then modify the code accordingly.

**Comment by lcampos777** [comment]
Already try but no luck, this is how the code will look like after doing what you suggested, however this still changes the GUI

![carbon (3)](https://user-images.githubusercontent.com/87612724/126075366-2faf0cb6-266f-49e6-9bea-40bd3a912f36.png)

![carbon (4)](https://user-images.githubusercontent.com/87612724/126075368-1b7b0d73-cfec-4c99-90b0-7eb8cd5ebcd7.png)

Just to give you an idea, this is how the GUI changes if I import anything from "pyautogui"

This is how it should look like: 

![good](https://user-images.githubusercontent.com/87612724/126075390-9352a5a8-6621-406d-afc3-f88ee35ef482.png)

and this after importing pyautogui:

![bad](https://user-images.githubusercontent.com/87612724/126075407-4f554df9-e373-4c07-9449-7ae5f4bf6109.png)

**Comment by Ankit404butfound** [comment]
There is something called DpiAwareness which is responsible for making your GUI sharp, you might have notice that tkinter is quite blurry because by default it is set to false, when you import pyautogui, it messes up with the value of DpiAwareness and make it true, which in turn mess up the positioning and sizes of your window, you may try to first add these lines to your code then you should proceed to create your tkinter app, this will do two things, make your UI better, your app will not be affected by pyautogui import.

```python
import ctypes
ctypes.windll.shcore.SetProcessDpiAwareness(1)
```

**Comment by lcampos777** [comment]
Thanks @Ankit404butfound already tried but unfortunately same issue, the GUI continues changing its size. Notices something odd in the process, if I comment the "pyautogui" import and include the code just as you suggested:

import ctypes
ctypes.windll.shcore.SetProcessDpiAwareness(1)

The GUI still changes its size, see below:

![carbon (6)](https://user-images.githubusercontent.com/87612724/126075921-ccb30c82-7b6c-407c-a02f-491cdee7d0a0.png)

However, if the the "pyautogui" import is still as a comment and change the "1" in your suggested code by a "0", the GUI doesn't change its size and all looks good. 

![carbon (7)](https://user-images.githubusercontent.com/87612724/126075985-9ae30f3b-a84b-4d41-bb7c-3bb026b0d38c.png)

As soon as I remove the hash sign from the "pyautogui" import line, no matter if "SetProcessDpiAwareness" is set to 1 or 0, the GUI changes

**Comment by Ankit404butfound** [comment]
Yes that's exactly what I tried for one of my app and it didn't work either, so I have to resize the entire app, it was really irritating.
One solution would be to copy the required part from pyautogui source code and include it in the code instead.

**Comment by lcampos777** [comment]
You know what, after running some tests tried to move things around and moving your suggested code, but setting it to Zero instead of One, before the "pyautogui" import does the trick, it should look like this:

![carbon (9)](https://user-images.githubusercontent.com/87612724/126076285-a4b0c9a8-f900-414b-8780-5f4fa4261bab.png)

You may want to give it a try for your app too, hope this helps.

Thank you very much @Ankit404butfound and @aaryanrr for your help!

**Comment by Ankit404butfound** [comment]
Oh well, why didn't I think of that. Thanks to you now. 😅
