### ISSUE TITLE
Pywhatkit.playonyt - this site cannot be reached

### ISSUE THREAD

**Issue by nikodemmrowka** [Ankit404butfound/PyWhatKit#45]
windows10
Python 3.9.0

Hi,
I urgently need help. I’m trying to use the pywhatkit library and playonyt function in the program to play a song on youtube in a new tab. Unfortunately I get the error “This site cannot be reached. Please check www.youtube.com% 3E% 3C for an error.” and url looks like “https://www.youtube.com%3E%3C/form%3E%3Ca%20href=”
Yesterday I fired up the code and it worked normally, it wasn’t just looking for some songs and most of it turned on. Nothing changing today doesn’t work for me.
Please help

**Comment by aaryanrr** [comment]
Hi @nikodemmrowka, Can you please provide some more details like the screenshot of the error message or what search causes this error because I just tested that function and it worked perfect for me.

**Comment by nikodemmrowka** [comment]
![image](https://user-images.githubusercontent.com/80956772/113475335-471b7b80-9475-11eb-8a58-49a112650059.png)
![image](https://user-images.githubusercontent.com/80956772/113475375-89dd5380-9475-11eb-9ef0-07c729792fbc.png)

normally I try to play music and it does.
No error in the code is possible because it worked the day before

**Comment by aaryanrr** [comment]
The URL that is getting opened is malformed. Are you using a virtual environment or installing it globally? Because I think either the Code has been changed or some other package is conflicting with it.
I again tested it in a virtual environment and it worked perfect for me.

**Comment by Ankit404butfound** [comment]
Hi @nikodemmrowka, can you try the code

```
def playonyt(topic):
    """Will play video on following topic, takes about 10 to 15 seconds to load"""
    url = 'https://www.youtube.com/results?q=' + topic
    count = 0
    cont = requests.get(url)
    data = str(cont.content)
    lst = data.split('"')
    for i in lst:
        count+=1
        if i == 'WEB_PAGE_TYPE_WATCH':
            break
    if lst[count-5] == "/results":
        raise Exception("No video found.")
    
    #print("Videos found, opening most recent video")
    web.open("https://www.youtube.com"+lst[count-5])
    return "https://www.youtube.com"+lst[count-5]
```

If that is not working, let us know. Make sure to import the libraries needed.

**Comment by nikodemmrowka** [comment]
Hi @Ankit404butfound 
![image](https://user-images.githubusercontent.com/80956772/113476223-6668d780-947a-11eb-944a-8d7ade3b05f3.png)
I used the same code

I also created new project with this lines:

**import pywhatkit


def fun():
    pywhatkit.playonyt('justin bieber')

fun()**

And still the same :((

**Comment by Ankit404butfound** [comment]
Ok let me try to replicate the issue.
Meanwhile, can you run this code and attach the output file as a reply to this comment.

```
import requests
file = open("YouTube_data.txt","w",encoding="utf-8")
file.write(requests.get("https://www.youtube.com/search?q=python").text)
file.close()
```

It will simply extract the HTML of the YouTube search page. I guess, YouTube has carried out some updates in their web structure and is testing it by enrolling it for a few users.

**Comment by anthonypretty** [comment]
It looks like it is going to a cookies page first.
This is a screenshot of what I see from printing data from the mainfunctions.py script.
    cont = requests.get(url)
    data = cont.content
    data = str(data)
    print(data)

![image](https://user-images.githubusercontent.com/60434393/114160042-5fc8dd00-991e-11eb-9fd0-9efc485ae731.png)

**Comment by Ankit404butfound** [comment]
Can you try the same code on any other device, if you get the same result then we will know that it's not the fault of device while sending get request. I will search for solution and release new update then.

**Comment by anthonypretty** [comment]
I have tried it on2 different windows 10 machines and a windows 8 but get the same error. Sorry I have no Linux builds at the moment

The screen shot is if I paste the data output in to a file and add .html on the end

**Comment by Ankit404butfound** [comment]
It seems, YouTube is rolling out a new feature, would you please attach the
.html file?

**Comment by nikodemmrowka** [comment]
<!DOCTYPE html><html lang="pl" dir="ltr"><head><style nonce="/K46VTtTZMimttF0I9PmmA">
a, a:link, a:visited, a:active, a:hover {
  color: #1a73e8;
  text-decoration: none;
}
body {
  font-family: Roboto,RobotoDraft,Helvetica,Arial,sans-serif;
  text-align: center;
  -ms-text-size-adjust: 100%;
  -moz-text-size-adjust: 100%;
  -webkit-text-size-adjust: 100%;
}
.box {
  border: 1px solid #dadce0;
  box-sizing: border-box;
  border-radius: 8px;
  margin: 24px auto 5px auto;
  max-width: 520px;
  padding: 24px;
}
h1 {
  color: #2c2c2c;
  font-size: 24px;
  hyphens: auto;
  margin: 24px 0;
}
p, .sub, .contentText {
  color: #5f6368;;
  font-size: 14px;
  line-height: 20px;
  letter-spacing: 0.2px;
  text-align: left;
}
.signin {
  text-align: right;
}
.image {
  display: block;
  margin: 14px auto;
}
a.button {
  color: #fff;
}
button, .button {
  border-radius: 4px;
  background-color: #1a73e8;
  border: none;
  color: #fff;
  cursor: pointer;
  font-family: Roboto,RobotoDraft,Helvetica,Arial,sans-serif;
  font-size: 14px;
  font-weight: 500;
  height: 36px;
  margin: 0 4px;
  padding: 10px 24px;
}
input.button {
  -webkit-appearance: none;
}
.error {
  border: 2px solid #d93025;
  border-radius: 5px;
  color: #d93025;
  margin: auto;
  padding: 5px;
}
.footer {
  margin-top: 16px;
}
.footer a {
  margin-left: 24px;
  white-space: nowrap;
}
.footer a, .footer select, .footer input {
  color: #757575;
  font-size: 12px;
}
.languagepicker {
  display: inline-flex;
  margin: 2px 0;
}
#languageform,
#languageselect {
  margin: 0 2px;
}
#languageselect {
  color: #757575;
}
.detailspage {
  margin: 24px auto 0 auto;
  max-width: 700px;
}
.detailspage h1, .detailspage h2 {
  font-size: 22px
}
.setting {
  border: 1px solid #dadce0;
  box-sizing: border-box;
  border-radius: 8px;
  margin-bottom: 11px;
  padding: 24px 24px 20px 24px;
  text-align: right;
}
.sub {
  padding: 24px 24px 20px 24px;
}
hr {
  margin: 12px -24px 12px;
  border: 0;
  border-top: 1px solid #dadce0;
}
fieldset {
  border: none;
  padding: 0;
}
label {
  margin: 24px;
}
td {
  vertical-align: top;
}
.setting h2, .setting h3, h4 {
  color: #3c4043;
  margin: 0;
  text-align: left;
}
.yt-text {
  color: #5f6368;
  font-size: 14px;
  font-weight: 300;
}
.productLogoContainer {
  margin: auto;
  max-width: 360px;
}

/** Narrow screen (for example a mobile device). */
@media only screen and (max-width: 480px) {
  body {
    margin: 18px 14px;
  }
  .imgContainer {
    min-width: 72px;
  }
  .hideOnSmallWidth {
    display: none;
  }
  .footer form {
    margin-bottom: 3px;
  }
}

/** Normal/non-narrow screen. */
@media not screen and (max-width: 480px) {
  body {
    margin: 18px 25px;
  }
  .imgContainer {
    width: 51%;
  }
  .hideOnNormalWidth {
    display: none;
  }
  .footer form {
    display: inline;
  }
}
</style><title>Zanim przejdziesz do YouTube</title><meta name="viewport" content="initial-scale=1, maximum-scale=5, width=device-width"><link rel="shortcut icon" href="//www.google.com/favicon.ico"></head><body><div class="signin"><a href="https://accounts.google.com/ServiceLogin?hl=pl&amp;continue=https://www.youtube.com/results?q%3Dpython&amp;gae=cb-23983172" class="button">Zaloguj się</a></div><div class="box"><img src="//www.gstatic.com/ac/cb/cb_yt_logo_d_header_118x26_4dfe7c3d17767ffd2294ae90fb54337e.png" srcset="//www.gstatic.com/ac/cb/cb_yt_logo_d_header_236x52_32f50a7f5baad56e4faf48252fbc19d6.png 2x" width="93" height="20" alt="YouTube"> <span class="yt-text">firma Google</span><div class="productLogoContainer"><img src="https://www.gstatic.com/ac/cb/scene_cookie_wall_youtube.svg" alt="" width="100%" height="100%" class="image" aria-hidden="true"></div><h1>Zanim przejdziesz do YouTube</h1><div class="contentText">Google wykorzystuje <a href="https://policies.google.com/technologies/cookies?hl=pl&utm_source=ucb" target="_blank">pliki cookie</a> i inne dane do:<ul><li>dostarczania i utrzymywania usług, na przykład do śledzenia przerw w ich działaniu lub do ochrony użytkowników przed spamem, oszustwami i nadużyciami;</li><li>pomiaru zaangażowania odbiorców i generowania statystyk na temat witryn w celu lepszego zrozumienia, jak są używane usługi Google.</li></ul>Jeśli się na to zgodzisz, pliki cookie i inne dane będziemy wykorzystywać także do:<ul><li>poprawiania jakości obecnych usług i opracowywania nowych;</li><li>wyświetlania reklam i mierzenia ich skuteczności;</li><li>wyświetlania spersonalizowanych treści (w zależności od Twoich ustawień);</li><li>wyświetlania spersonalizowanych lub niespersonalizowanych reklam (w zależności od Twoich ustawień) w usługach Google i w innych miejscach w internecie.</li></ul>Reklamy i treści niespersonalizowane mogą być dobierane na podstawie czynników takich jak aktualnie przeglądane treści czy Twoja lokalizacja (wyświetlanie reklam jest oparte na przybliżonej lokalizacji). Reklamy i treści spersonalizowane również są dobierane według tych czynników oraz dodatkowo na podstawie Twojej aktywności, na przykład haseł wyszukiwanych w Google czy filmów oglądanych w YouTube. Reklamy i treści spersonalizowane to między innymi trafniejsze wyniki i rekomendacje, indywidualna strona główna w YouTube oraz reklamy dopasowane do Twoich zainteresowań.<p>Jeśli chcesz przejrzeć dostępne możliwości, w tym opcje rezygnacji z plików cookie używanych do personalizacji lub informacje o opcjach na poziomie przeglądarki pozwalających zrezygnować z niektórych lub wszystkich plików cookie używanych w innych celach, kliknij „Dostosuj”. W każdej chwili możesz też wejść na stronę g.co/privacytools.</p></div><div><a href="https://consent.youtube.com/dl?continue=https://www.youtube.com/results?q%3Dpython&amp;gl=PL&amp;hl=pl&amp;pc=yt&amp;uxe=23983172&amp;src=1" class="button">Dostosuj</a><form action="https://consent.youtube.com/s" method="POST" style="display:inline;"><input type="hidden" name="gl" value="PL"><input type="hidden" name="m" value="0"><input type="hidden" name="pc" value="yt"><input type="hidden" name="continue" value="https://www.youtube.com/results?q=python"><input type="hidden" name="ca" value="r"><input type="hidden" name="x" value="8"><input type="hidden" name="v" value="cb.20210406-12-p0.pl+FX+202"><input type="hidden" name="t" value="ADw3F8h7Lk_HSZvHWU5IcXp6ZzaXpFK5Ew:1618167152692"><input type="hidden" name="hl" value="pl"><input type="hidden" name="src" value="1"><input type="hidden" name="uxe" value="23983172"><input type="submit" value="Zgadzam się" class="button" aria-label="Zgadzasz się na wykorzystanie plików cookie i innych danych do opisanych celów"/></form></div></div><div class="footer"><form action="https://consent.youtube.com/ml" method="get"><select id="languageselect" name="hl"><option value="af">Afrikaans</option><option value="az">azərbaycan</option><option value="bs">bosanski</option><option value="ca">català</option><option value="cs">Čeština</option><option value="cy">Cymraeg</option><option value="da">Dansk</option><option value="de">Deutsch</option><option value="et">eesti</option><option value="en-GB">English&nbsp;(United Kingdom)</option><option value="en">English&nbsp;(United States)</option><option value="es">Español&nbsp;(España)</option><option value="es-419">Español&nbsp;(Latinoamérica)</option><option value="eu">euskara</option><option value="fil">Filipino</option><option value="fr-CA">Français&nbsp;(Canada)</option><option value="fr">Français&nbsp;(France)</option><option value="ga">Gaeilge</option><option value="gl">galego</option><option value="hr">Hrvatski</option><option value="id">Indonesia</option><option value="zu">isiZulu</option><option value="is">íslenska</option><option value="it">Italiano</option><option value="sw">Kiswahili</option><option value="lv">latviešu</option><option value="lt">lietuvių</option><option value="hu">magyar</option><option value="ms">Melayu</option><option value="nl">Nederlands</option><option value="no">norsk</option><option value="uz">o‘zbek</option><option value="pl" selected>polski</option><option value="pt-BR">Português&nbsp;(Brasil)</option><option value="pt-PT">Português&nbsp;(Portugal)</option><option value="ro">română</option><option value="sq">shqip</option><option value="sk">Slovenčina</option><option value="sl">slovenščina</option><option value="sr-Latn">srpski (latinica)</option><option value="fi">Suomi</option><option value="sv">Svenska</option><option value="vi">Tiếng Việt</option><option value="tr">Türkçe</option><option value="el">Ελληνικά</option><option value="be">беларуская</option><option value="bg">български</option><option value="ky">кыргызча</option><option value="kk">қазақ тілі</option><option value="mk">македонски</option><option value="mn">монгол</option><option value="ru">Русский</option><option value="sr">српски</option><option value="uk">Українська</option><option value="ka">ქართული</option><option value="hy">հայերեն</option><option value="iw">עברית</option><option value="ur">اردو</option><option value="ar">العربية</option><option value="fa">فارسی</option><option value="am">አማርኛ</option><option value="ne">नेपाली</option><option value="mr">मराठी</option><option value="hi">हिन्दी</option><option value="as">অসমীয়া</option><option value="bn">বাংলা</option><option value="pa">ਪੰਜਾਬੀ</option><option value="gu">ગુજરાતી</option><option value="or">ଓଡ଼ିଆ</option><option value="ta">தமிழ்</option><option value="te">తెలుగు</option><option value="kn">ಕನ್ನಡ</option><option value="ml">മലയാളം</option><option value="si">සිංහල</option><option value="th">ไทย</option><option value="lo">ລາວ</option><option value="my">မြန်မာ</option><option value="km">ខ្មែរ</option><option value="ko">한국어</option><option value="ja">日本語</option><option value="zh-CN">简体中文</option><option value="zh-TW">繁體中文</option><option value="zh-HK">繁體中文&nbsp;(香港)</option></select><input type="hidden" name="oldhl" value="pl"><input type="hidden" name="gl" value="PL"><input type="hidden" name="m" value="0"><input type="hidden" name="pc" value="yt"><input type="hidden" name="continue" value="https://www.youtube.com/results?q=python"><input type="hidden" name="src" value="1"><input type="submit" value="Zmień język"></form><a href="https://policies.google.com/privacy?hl=pl">Polityka prywatności</a> <a href="https://policies.google.com/terms?hl=pl">Warunki korzystania z usługi</a></div></body></html>

**Comment by nikodemmrowka** [comment]
My html file, the same as colleaque above

**Comment by nikodemmrowka** [comment]
[YouTube_data.txt](https://github.com/Ankit404butfound/PyWhatKit/files/6292546/YouTube_data.txt)

**Comment by Ankit404butfound** [comment]
Ok, let me see what could be the possible issue.

**Comment by Ankit404butfound** [comment]
Hi, can you try with the parameter "search_query" instead of "query". That is, try with https://www.youtube.com/results?search_query=python.

**Comment by anthonypretty** [comment]
sorry for not getting back
I have tried changing it in your module but get the same error.

I changed this:
![image](https://user-images.githubusercontent.com/60434393/114394094-b8081500-9b92-11eb-9294-d595a3f064a7.png)
 but still get this as the output:
![image](https://user-images.githubusercontent.com/60434393/114394171-cf470280-9b92-11eb-86b9-c8e23f54f922.png)

with the webpage opening saying it can't find that address

**Comment by Ankit404butfound** [comment]
Can you confirm, while clicking https://www.youtube.com/results?search_query=python, if it's taking you to the right page, or the same page a above.

**Comment by Ankit404butfound** [comment]
Hi, it seems you are using VPN, if that's the case then it is the reason why the code is failing.
I created an unofficial API, try to send a get request to http://mypywhatkit.herokuapp.com/playonyt?topic=python, it will return the URL.
Try
`import requests
url = requests.get("http://mypywhatkit.herokuapp.com/playonyt?topic=python").text
print(url)`

**Comment by nikodemmrowka** [comment]
Yea its return correct URL.

How should I used this, like this doesnt work:

url = requests.get("http://mypywhatkit.herokuapp.com/playonyt?topic=" + topic).text
    count = 0
    cont = requests.get(url)
    data = cont.content
    data = str(data)
    lst = data.split('"')
    for i in lst:
        count+=1
        if i == 'WEB_PAGE_TYPE_WATCH':
            break
    if lst[count-5] == "/results":
        raise Exception("No video found.")
    
    #print("Videos found, opening most recent video")
    web.open("https://www.youtube.com"+lst[count-5])
    return "https://www.youtube.com"+lst[count-5]

**Comment by Ankit404butfound** [comment]
Try this
```
import webbrowser as web
import requests
url = requests.get("http://mypywhatkit.herokuapp.com/playonyt?topic=python").text
print(url)
web.open(url)
```

**Comment by nikodemmrowka** [comment]
wooow you are genius!!! It's running

**Comment by nikodemmrowka** [comment]
This unofficial API will always work? Do you plan to remove it sometime?

**Comment by Ankit404butfound** [comment]
No, not anytime soon, but we are searching for a permanent fix for this, this API will continue to work until we find any solution.
