### ISSUE TITLE
pywhatkit.sendwhatmsg_to_group function is not working

### ISSUE THREAD

**Issue by ADGVLOGS** [Ankit404butfound/PyWhatKit#46]
**bug issue**

**To Reproduce**
1. write a script pywhatkit.sendwhatmsg_to_group("groupid","message here", hours, minutes)
2. wait for the script to execute and open WhatsApp web

**Expected behavior**
The python script opens the web browser correctly to the right group chat :) 
the script does not type anything into the message textbox and submits nothing. 

**Desktop:**
 - OS: Microsoft Windows 10
 - Browser [Chrome]

Please fix ASAP i got a project I want to work on ASAP i love your API its quick and efficient.

**Comment by Ankit404butfound** [comment]
Ok I will look into this soon.

**Comment by ADGVLOGS** [comment]
> Ok I will look into this soon.

ETA? on the fix?

**Comment by Ankit404butfound** [comment]
Yes, I have found a solution for Windows, once I find a solution for Linux
and Mac too, I will release a new update.

**Comment by ADGVLOGS** [comment]
I only need it for windows, cant you make a plan to release the update only resolving the windows side?

**Comment by Ankit404butfound** [comment]
Ok, I will release the update for windows, today.

**Comment by Ankit404butfound** [comment]
Hi, can you please check the updated version.

**Comment by ADGVLOGS** [comment]
> Hi, can you please check the updated version.

I used this command to update 

pip install pywhatkit --upgrade  

I got a triple monitor setup.

it inserts the message into Visual Studio IDE instead of WhatsApp Web.
not sure if I did the update correctly.

**Comment by ADGVLOGS** [comment]
> > Hi, can you please check the updated version.
> 
> I used this command to update
> 
> pip install pywhatkit --upgrade
> 
> I got a triple monitor setup.
> 
> it inserts the message into Visual Studio IDE instead of WhatsApp Web.
> not sure if I did the update correctly.

when I drag the browser to the main window the code API works.
ill give it a pass but work on selecting the monitor where the web browser with WhatsApp is.

Thanks for the API 
:-)

**Comment by Ankit404butfound** [comment]
So if works but you need to select the monitor where the whatsapp is?
I think we need to rectify this issue. I will try to search for better solution. Thank you for using Pywhatkit. 😄

**Comment by ADGVLOGS** [comment]
My project is done please take a look

https://github.com/ADGVLOGS/whatsapp-birthday-bot

Thank you for your API :)

**Comment by Ankit404butfound** [comment]
Wow! That's awesome. Only problem is that, it'd be  great if we don't have to copy it to C/Python3x.
Another thing would be that, it should automatically download the required libraries, try to make it for someone who don't know much Python, for example a general user

**Comment by ADGVLOGS** [comment]
yes you are correct about that. I should try and make a function to find the python directory from system environment variables.

I'm also going to try and do an installshield for this application that will automate all of that.

Thanks for the advice :)

**Comment by Ankit404butfound** [comment]
You are welcome, good luck for the work. 😄

**Comment by sumittokle** [comment]
> So it works but you need to select the monitor where the whatsapp is? I think we need to rectify this issue. I will try to search for better solution. Thank you for using Pywhatkit. 😄

Has this issue been resolved? I'm seeing this issue on MAC

**Comment by pablopalou** [comment]
I am also seeing this issue on Mac.

**Comment by mgovindasamy** [comment]
has this issue been resolved, I still see the same behavior above. The issue is on MAC
