### ISSUE TITLE
AttributeError: module 'pyautogui' has no attribute 'getWindowsWithTitle'

### ISSUE THREAD

**Issue by AntonSk98** [Ankit404butfound/PyWhatKit#49]
Hello!

First of all, thanks for the library.

ISSUE: While using it, I encountered an issue trying to send a message into a group chat. The output is "AttributeError: module 'pyautogui' has no attribute 'getWindowsWithTitle'".

However, sending personal messages to particular users works.

I am trying to send a group message on Chrome, Linux (Pop!_OS)

**Comment by aaryanrr** [comment]
Hey @AntonSk98 , Thanks for reporting the Issue. We have recently figured out this issue while testing it on Ubuntu. We are working to find a fix for it.

**Comment by SuvanshKumar** [comment]
PyWhatKit relies on PyAutoGui for the window functionality. However, PyAutoGui supports these functions only on windows as of now. 
We'll have to wait before they support it on Linux too!

**Comment by vikramsalunke20** [comment]
On MacOS window is not focused when using pg.click() but using pg.dragRel() window becomes focussed. So following code is useful to type something in window

pg.moveTo()
pg.dragRel()
time.sleep(10)
pg.click()
pg.typewrite()
