### ISSUE TITLE
Pip Install IOError: Trying to get README from a hardcoded Windows path

### ISSUE THREAD

**Issue by richardsonlima** [Ankit404butfound/PyWhatKit#5]
Hi there, I noticed that the package pip installer setup is trying to perform some ODD/weird behavior. It's receiving RC with value 1 because for some reason try to get README file using a hardcoded windows path. Below the traceback 

         cwd: /private/tmp/pip-install-9YjMmR/pywhatkit/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-install-9YjMmR/pywhatkit/setup.py", line 29, in <module>
        long_description=readme(),
      File "/private/tmp/pip-install-9YjMmR/pywhatkit/setup.py", line 5, in readme
        with open(r'C:\Users\pc\Desktop\pywhatkit\README.txt') as f:
    IOError: [Errno 2] No such file or directory: 'C:\\Users\\pc\\Desktop\\pywhatkit\\README.txt'

with open(r'C:\Users\pc\Desktop\pywhatkit\README.txt') as f:

**Comment by Ankit404butfound** [comment]
Sorry for the trouble, will be fixed by 12 noon toady.

**Comment by richardsonlima** [comment]
Thank you!

**Comment by Ankit404butfound** [comment]
> Thank you!

Fixed!
