### ISSUE TITLE
playonyt not working: This site can’t be reached

### ISSUE THREAD

**Issue by QtePieGames** [Ankit404butfound/PyWhatKit#50]
Hi! I am building an Alexa-like AI that I will use for personal use. I was working on the "Play Song" function using Pywhatkit's "playinyt" feature but whenever it opens youtube on my browser to play the video it says: This site can’t be reached (Check if there is a typo in www.youtube.com%3E%3C.) I don't know how to fix, so i could really use the help. this is my code for it:

` 
def run_cherryAI():
    command = take_command()
    print(command)
    if 'play' in command:
        song = command.replace('play', '')
        talk('playing'+ song)
        pywhatkit.playonyt(song)

run_cherryAI() `

**Comment by Ankit404butfound** [comment]
Are you using VPN? If that's the case, let me know.

**Comment by QtePieGames** [comment]
no, im not using any sort of vpn

**Comment by Ankit404butfound** [comment]
Please check this https://github.com/Ankit404butfound/PyWhatKit/issues/45#issuecomment-818859387, meanwhile I am trying to figure out the possible reason for this problem, I will release a fix soon.

**Comment by Naman23-coder** [comment]
can give me the whole code,maybe i could help

**Comment by SpiderHAckerDzm** [comment]
if you look at the code here:

`def playonyt(topic):
    """Will play video on following topic, takes about 10 to 15 seconds to load"""
    url = 'https://www.youtube.com/results?q=' + topic
    count = 0
    cont = requests.get(url)
    data = cont.content
    data = str(data)
    lst = data.split('"')
    for i in lst:
        count+=1
        if i == 'WEB_PAGE_TYPE_WATCH':
            break
    if lst[count-5] == "/results":
        raise Exception("No video found.")
    
    #print("Videos found, opening most recent video")
    web.open("https://www.youtube.com"+lst[count-5])
    return "https://www.youtube.com"+lst[count-5]`
    
    This won't work. But since you're working on an API, I know why you made this but release the latest pack as non-API so people don't have to go in the code and do this manually:
    `def playonyt(topic):
    """Will play video on following topic, takes about 10 to 15 seconds to load"""
    url = 'https://www.youtube.com/results?q=' + topic
    count = 0
    cont = requests.get(url)
    data = cont.content
    data = str(data)
    lst = data.split('"')
    for i in lst:
        count+=1
        if i == 'WEB_PAGE_TYPE_WATCH':
            break
    if lst[count-5] == "/results":
        raise Exception("No video found.")
    
    #print("Videos found, opening most recent video")
    # web.open("https://www.youtube.com"+lst[count-5])
    web.open(url)
    # return "https://www.youtube.com"+lst[count-5]
    return url`
    
    Thank you.

**Comment by aaryanrr** [comment]
Thanks @SpiderHAckerDzm for the solution.
@QtePieGames can you please try this!

**Comment by SecchioDiFerro** [comment]
> **Don't know why but the code layout is acting weird... Well anyway heres a Solution** _**[ NOT A VPN PROBLEM ]**_
> 
> if you look at the code here:
> 
> **This won't work. But since you're working on an API, I know why you made this but release the latest pack as non-API so people don't have to go in the code and do this manually:**
> 
> ```
> From This:
> 
> `def playonyt(topic):
>   """Will play video on following topic, takes about 10 to 15 seconds to load"""
>   url = 'https://www.youtube.com/results?q=' + topic
>   count = 0
>   cont = requests.get(url)
>   data = cont.content
>   data = str(data)
>   lst = data.split('"')
>   for i in lst:
>       count+=1
>       if i == 'WEB_PAGE_TYPE_WATCH':
>           break
>   if lst[count-5] == "/results":
>       raise Exception("No video found.")
>   
>   #print("Videos found, opening most recent video")
>   web.open("https://www.youtube.com"+lst[count-5])
>   return "https://www.youtube.com"+lst[count-5]`
> 
> To This:
> 
> def playonyt(topic):
> """Will play video on following topic, takes about 10 to 15 seconds to load"""
> url = 'https://www.youtube.com/results?q=' + topic
> count = 0
> cont = requests.get(url)
> data = cont.content
> data = str(data)
> lst = data.split('"')
> for i in lst:
>     count+=1
>     if i == 'WEB_PAGE_TYPE_WATCH':
>         break
> if lst[count-5] == "/results":
>     raise Exception("No video found.")
> 
> #print("Videos found, opening most recent video")
> # web.open("https://www.youtube.com"+lst[count-5])
> web.open(url)
> # return "https://www.youtube.com"+lst[count-5]
> return url
> 
> Thank you.
> ```

finally, it worked for me, really thank you. How i can make the first result on yt open? sorry, im really noob and really bad in english too AHAHAH

**Comment by Ankit404butfound** [comment]
Thank you for the solution, bit that will open the search page of the YouTube and will not automatically play the video.
