### ISSUE TITLE
Finding browser probleme

### ISSUE THREAD

**Issue by othmane53** [Ankit404butfound/PyWhatKit#52]
I used the example as shown on official page, and I got error about the browser 

here is the output error:

  File "C:\Users\......\Python\Python39\lib\site-packages\pywhatkit\main.py", line 56, in sendwhatmsg
    if browser.lower() not in ["chrome", "firefox", "brave", "opera"]:
AttributeError: 'NoneType' object has no attribute 'lower'

**the solution for it is that I went to the main.py  and in def sendwhatmsg I changed the value given to the browser parameter from 'None' to 'firefox' and it worked fine**

**Comment by Ankit404butfound** [comment]
Thanks for pointing out this issue and the solution, we have released a fix for it.
