### ISSUE TITLE
The offical website doesn't work? also what pywhatkit builed on?

### ISSUE THREAD

**Issue by CJSparrow** [Ankit404butfound/PyWhatKit#56]
Hi,
The official website doesn't work at all or at the moment?
https://pywhatkit.herokuapp.com 

the error message is:
![image](https://user-images.githubusercontent.com/65213455/116764758-caa39a80-aa2a-11eb-8bf0-37a9c381c9a8.png)

another thing, is this lib use selenium?

thx

**Comment by Ankit404butfound** [comment]
No pywhatkit does not use selenium, some features like sendwhatmsg and text_to_handwriting requires some initial setup, we released that it was making the library hard to use hence we created an API. It's temporary down.
