### ISSUE TITLE
send_file function not working

### ISSUE THREAD

**Issue by zainbabur** [Ankit404butfound/PyWhatKit#6]
FYA please.

>>> pywhatkit.send_file("+923125661253","/home/zain/Documents/employees.csv",20,50)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zain/.local/lib/python3.8/site-packages/pywhatkit/__init__.py", line 214, in send_file
    chrpath = chrpath.strip()
UnboundLocalError: local variable 'chrpath' referenced before assignment

**Comment by Ankit404butfound** [comment]
Have you added chromedriver path by called add_driver_path function?

**Comment by muktasiddu** [comment]
I m getting error as follow AttributeError :module 'pywhatkit' has no attribute 'send_file'.

**Comment by anuragchaurasia3108** [comment]
pywhatkit.send_file("+923125661253","/home/zain/Documents/employees.csv",20,50)
inplace of  "/home/zain/Documents/employees.csv"
you have wrote a message which you want to send your friend 
just like  pywhatkit.sendwhatmsg("mobile number", "hey bro how r u ",9,45)
after run your code 

In 53 seconds web.whatsapp.com will open and after 20 seconds message will be delivered  
show's this msg in terminal
