### ISSUE TITLE
Issues with number of sentences, using inverted commas, cannot take user input dynamically.

### ISSUE THREAD

**Issue by 0LUCIFER** [Ankit404butfound/PyWhatKit#64]
Great work first of all. I was working with this module when I came across these issues:
We cannot use less than 5 sentences
Cannot take dynamic input from user, so it can only be run by putting texts as input in the code
Size of image cannot be resized, better if we could get a pdf output.
Great project anyways.

**Comment by aaryanrr** [comment]
Hi, @0LUCIFER , thanks for highlighting the issues. Can you please elaborate on what do you mean by dynamic input. For the image resize and pdf output (good ideas) we'll update you on what can be done.

**Comment by 0LUCIFER** [comment]
Great that you liked the ideas. By dynamic input what I meant was that I
tried taking user input using the input() method in python and then feed it
into the pywhatKit text to handwritten function but the image was not
getting generated in a proper way which led to the image not opening.

Here is the code I tried-

import pywhatkit

convert=input("Enter text")
pywhatkit.text_to_handwriting(convert,"destination path and file name", rgb
values in a list)

**Comment by Ankit404butfound** [comment]
We should be able to take input like the above, can you please tell us the exact error you get?

**Comment by aaryanrr** [comment]
As no further information regarding the issue has been provided so I am closing it.
