### ISSUE TITLE
playonyt doesn't work

### ISSUE THREAD

**Issue by Roberto2Meloni** [Ankit404butfound/PyWhatKit#66]
When i run this code in my function

pywhatkit.playonyt("ariana grande")

my Browser give me this output:

https://www.youtube.com%3E%3C/form><a%20href=

How can i fix that?

**Comment by Charanleo25** [comment]
this actually due to some privacy policy related problems that are specific to different countries
we have a workaround for that

solution:
phwhatkit.playonyt("ariana grande", use_api = True)

**Comment by Roberto2Meloni** [comment]
Thank you so much, it work perfect.
