### ISSUE TITLE
typo in readme

### ISSUE THREAD

**Issue by gauravk268** [Ankit404butfound/PyWhatKit#7]
in readme file, command for information is written as:
pywatkit.info("Python",lines=3,speak=None)#Will give information about the topic

instead of:
pywhatkit.info("Python",lines=3,speak=None)#Will give information about the topic

i.e. one 'h' is missing from pywhatkit.

**Comment by a110ats** [comment]
Another problem that I have found is,
in this part, when you enter "python" as the topic to search, it'll raise a <wikipedia.exceptions.DisambiguationError> error.
`wikipedia.exceptions.DisambiguationError: "Python" may refer to:  
Pythonidae  
Python (genus)  
Python (mythology)  
Python of Aenus  
Python (painter)  
Python of Byzantium  
Python of Catana  
Python (film)  
Pythons 2  
Monty Python  
Python (Monty) Pictures  
Python (programming language)  
CPython  
CMU Common Lisp  
PERQ 3  
Python (Busch Gardens Tampa Bay)  
Python (Coney Island, Cincinnati, Ohio)  
Python (Efteling)  
Python (automobile maker)  
Python (Ford prototype)  
Colt Python  
Python (missile)  
Python (nuclear primary)  
Python Anghelo  
PYTHON  
Cython  
Pyton`

**Comment by Ankit404butfound** [comment]
> in readme file, command for information is written as:
> pywatkit.info("Python",lines=3,speak=None)#Will give information about the topic
> 
> instead of:
> pywhatkit.info("Python",lines=3,speak=None)#Will give information about the topic
> 
> i.e. one 'h' is missing from pywhatkit.

It has been fixed, although the latest version of the library is 2.7, this is the first version of it so I was going to update it anyway.

**Comment by Ankit404butfound** [comment]
> Another problem that I have found is,
> in this part, when you enter "python" as the topic to search, it'll raise a <wikipedia.exceptions.DisambiguationError> error.
> `wikipedia.exceptions.DisambiguationError: "Python" may refer to: Pythonidae Python (genus) Python (mythology) Python of Aenus Python (painter) Python of Byzantium Python of Catana Python (film) Pythons 2 Monty Python Python (Monty) Pictures Python (programming language) CPython CMU Common Lisp PERQ 3 Python (Busch Gardens Tampa Bay) Python (Coney Island, Cincinnati, Ohio) Python (Efteling) Python (automobile maker) Python (Ford prototype) Colt Python Python (missile) Python (nuclear primary) Python Anghelo PYTHON Cython Pyton`

You need to specify which "Python" do want information upon, is it programming language or the snake or the artist etc.

**Comment by a110ats** [comment]
> > Another problem that I have found is,
> > in this part, when you enter "python" as the topic to search, it'll raise a <wikipedia.exceptions.DisambiguationError> error.
> > `wikipedia.exceptions.DisambiguationError: "Python" may refer to: Pythonidae Python (genus) Python (mythology) Python of Aenus Python (painter) Python of Byzantium Python of Catana Python (film) Pythons 2 Monty Python Python (Monty) Pictures Python (programming language) CPython CMU Common Lisp PERQ 3 Python (Busch Gardens Tampa Bay) Python (Coney Island, Cincinnati, Ohio) Python (Efteling) Python (automobile maker) Python (Ford prototype) Colt Python Python (missile) Python (nuclear primary) Python Anghelo PYTHON Cython Pyton`
> 
> You need to specify which "Python" do want information upon, is it programming language or the snake or the artist etc.

Yeah, I Understood.
