### ISSUE TITLE
[Least Priority] Change the title PNG on GitHub page

### ISSUE THREAD

**Issue by ashishthehulk** [Ankit404butfound/PyWhatKit#70]
I know it's not that important, but I think we should work on appearance too. That title PNG is not visible as it matches with the background black color.

solutions:
1. Just change to a different color title
2. Add a white padding around the current title image so it would work for both dark and light themes

By the way thanks for the awesome library

**Comment by ashishthehulk** [comment]
![image](https://user-images.githubusercontent.com/38736403/120944460-4394c100-c752-11eb-84a1-efaf642504c5.png)

**Comment by Ankit404butfound** [comment]
> I know it's not that important, but I think we should work on appearance too. That title PNG is not visible as it matches with the background black color.
> 
> solutions:
> 
> 1. Just change to a different color title
> 2. Add a white padding around the current title image so it would work for both dark and light themes
> 
> By the way thanks for the awesome library

Hey, thank you for the suggestion, we will surely update the image.
And thanks for being an user of PyWhatKit too. 😃
