### ISSUE TITLE
send whatsapp message to group

### ISSUE THREAD

**Issue by iitsmekali321** [Ankit404butfound/PyWhatKit#72]
Hi Ankit, there is a option to send whatsapp message to groups by using pywhatkit.sendwhatmsg_to_group. But, I am not sure how to use it and i tried putting group names in it. But, it didn't succeed. can anyone help me how to send whatsapp message to group using pywhatkit.

**Comment by aaryanrr** [comment]
Hey @iitsmekali321 , You need to put in the group id for sending messages to a group. Example: `pywhatkit.sendwhatmsg_to_group("GROUP_ID")` . A group ID is present in the group invite link and  can be provided to you by the Group Admin. Example: `https://chat.whatsapp.com/AB123CDEFGHijklmn`, here `AB123CDEFGHijklmn` is the group ID.
Have a look in the documentation [here](https://github.com/Ankit404butfound/PyWhatKit/wiki/Sending-WhatsApp-Messages)

**Comment by iitsmekali321** [comment]
> Hey @iitsmekali321 , You need to put in the group id for sending messages to a group. Example: `pywhatkit.sendwhatmsg_to_group("GROUP_ID")` . A group ID is present in the group invite link and can be provided to you by the Group Admin. Example: `https://chat.whatsapp.com/AB123CDEFGHijklmn`, here `AB123CDEFGHijklmn` is the group ID.
> Have a look in the documentation [here](https://github.com/Ankit404butfound/PyWhatKit/wiki/Sending-WhatsApp-Messages)

Thanks it worked..!!!!
