### ISSUE TITLE
OSError: [WinError 87] The parameter is incorrect

### ISSUE THREAD

**Issue by Ershubhambhagat** [Ankit404butfound/PyWhatKit#8]
OSError                                   Traceback (most recent call last)
<ipython-input-24-c9986587df98> in <module>
----> 1 pywhatkit.sendwhatmsg_with_selenium("+917488*****,"first msg by py",9,13)

C:\ANACNDA\lib\site-packages\pywhatkit\__init__.py in sendwhatmsg_with_selenium(phone_no, message, time_hour, time_min, print_messages)
    188     if headless_mode:
    189         options.add_argument("--headless")
--> 190     driver = webdriver.Chrome(path,options=options)
    191     url = ('https://web.whatsapp.com/send?phone='+phone_no)
    192     driver.get(url)

C:\ANACNDA\lib\site-packages\selenium\webdriver\chrome\webdriver.py in __init__(self, executable_path, port, options, service_args, desired_capabilities, service_log_path, chrome_options, keep_alive)
     71             service_args=service_args,
     72             log_path=service_log_path)
---> 73         self.service.start()
     74 
     75         try:

C:\ANACNDA\lib\site-packages\selenium\webdriver\common\service.py in start(self)
     74                                             stdout=self.log_file,
     75                                             stderr=self.log_file,
---> 76                                             stdin=PIPE)
     77         except TypeError:
     78             raise

C:\ANACNDA\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors, text)
    798                                 c2pread, c2pwrite,
    799                                 errread, errwrite,
--> 800                                 restore_signals, start_new_session)
    801         except:
    802             # Cleanup if the child failed starting.

C:\ANACNDA\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
   1205                                          env,
   1206                                          os.fspath(cwd) if cwd is not None else None,
-> 1207                                          startupinfo)
   1208             finally:
   1209                 # Child is launched. Close the parent's copy of those pipe

OSError: [WinError 87] The parameter is incorrect

**Comment by Ankit404butfound** [comment]
Call pywhatkit.add_driver_path("And add path to chromedriver here")
If haven't installed the driver, install it from here : https://chromedriver.chromium.org/downloads.

**Comment by sonumahajan** [comment]
i can add function to this project 
  to send a specific message to a mail at specific time.

**Comment by Ankit404butfound** [comment]
> i can add function to this project
> to send a specific message to a mail at specific time.

Please create a pull request and make the update/change to the package, I will review it and if I found it 100% working, I will merge it to the main branch and release a new update of the library along with that changes you made. 👍

**Comment by sonumahajan** [comment]
i make the pull request so you can check it and give me feedback.

**Comment by Ankit404butfound** [comment]
> i make the pull request so you can check it and give me feedback.

Yes, I have reviewed and merged the request. Small changes required, like adding the exception handling inside the function and scheduling feature. I will manage.

**Comment by Ankit404butfound** [comment]
> i make the pull request so you can check it and give me feedback.

Apart from this, I loved your GitHub bio, must have taken good amount of time.

**Comment by sonumahajan** [comment]
thanks for merging my pull request and also thanks for your appreciating my GitHub bio  :-)

**Comment by sonumahajan** [comment]
bro you did'nt updated the pypl diecription of module.

**Comment by Ankit404butfound** [comment]
Oh! Sorry about that, I have been a lot busy since a few days so not able
to get time to update the package, a lot of issues are pending to be merged
with the actual code.

I will update then as soon as possible.
