### ISSUE TITLE
Error when installing with pip

### ISSUE THREAD

**Issue by DavidDahan1** [Ankit404butfound/PyWhatKit#83]
**Describe the bug**
I have tried to install the package via pip: https://pypi.org/project/pywhatkit/
and go the following errors:

`pip install pywhatkit
Collecting pywhatkit
  Downloading pywhatkit-4.8-py3-none-any.whl (11 kB)
Collecting pyautogui
  Downloading PyAutoGUI-0.9.52.tar.gz (55 kB)
     |████████████████████████████████| 55 kB 524 kB/s 
Collecting wikipedia
  Downloading wikipedia-1.4.0.tar.gz (27 kB)
Collecting requests
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting Pillow
  Using cached Pillow-8.2.0-cp38-cp38-manylinux1_x86_64.whl (3.0 MB)
Collecting PyTweening>=1.0.1
  Downloading PyTweening-1.0.3.zip (15 kB)
Collecting mouseinfo
  Downloading MouseInfo-0.1.3.tar.gz (10 kB)
Collecting pygetwindow>=0.0.5
  Downloading PyGetWindow-0.0.9.tar.gz (9.7 kB)
Collecting pymsgbox
  Downloading PyMsgBox-1.0.9.tar.gz (18 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting pyscreeze>=0.1.21
  Downloading PyScreeze-0.1.27.tar.gz (25 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting python3-Xlib
  Downloading python3-xlib-0.15.tar.gz (132 kB)
     |████████████████████████████████| 132 kB 1.5 MB/s 
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.9.3-py3-none-any.whl (115 kB)
     |████████████████████████████████| 115 kB 3.3 MB/s 
Collecting certifi>=2017.4.17
  Using cached certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.5-py2.py3-none-any.whl (138 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting chardet<5,>=3.0.2
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting pyperclip
  Downloading pyperclip-1.8.2.tar.gz (20 kB)
Collecting pyrect
  Downloading PyRect-0.1.4.tar.gz (15 kB)
Collecting soupsieve>1.2; python_version >= "3.0"
  Downloading soupsieve-2.2.1-py3-none-any.whl (33 kB)
Building wheels for collected packages: pyautogui, wikipedia, PyTweening, mouseinfo, pygetwindow, pymsgbox, pyscreeze, python3-Xlib, pyperclip, pyrect
  Building wheel for pyautogui (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/david/whatsapp/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nvgwm6ep/pyautogui/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nvgwm6ep/pyautogui/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-jn57uvt7
       cwd: /tmp/pip-install-nvgwm6ep/pyautogui/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for pyautogui
  Running setup.py clean for pyautogui
  Building wheel for wikipedia (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/david/whatsapp/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nvgwm6ep/wikipedia/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nvgwm6ep/wikipedia/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-867z4620
       cwd: /tmp/pip-install-nvgwm6ep/wikipedia/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for wikipedia
  Running setup.py clean for wikipedia
  Building wheel for PyTweening (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/david/whatsapp/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nvgwm6ep/PyTweening/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nvgwm6ep/PyTweening/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ojo5ezjc
       cwd: /tmp/pip-install-nvgwm6ep/PyTweening/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for PyTweening
  Running setup.py clean for PyTweening
  Building wheel for mouseinfo (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/david/whatsapp/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nvgwm6ep/mouseinfo/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nvgwm6ep/mouseinfo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-94zepy2y
       cwd: /tmp/pip-install-nvgwm6ep/mouseinfo/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for mouseinfo
  Running setup.py clean for mouseinfo
  Building wheel for pygetwindow (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/david/whatsapp/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nvgwm6ep/pygetwindow/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nvgwm6ep/pygetwindow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-oomlt_69
       cwd: /tmp/pip-install-nvgwm6ep/pygetwindow/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for pygetwindow
  Running setup.py clean for pygetwindow
  Building wheel for pymsgbox (PEP 517) ... done
  Created wheel for pymsgbox: filename=PyMsgBox-1.0.9-py3-none-any.whl size=7420 sha256=e186970f32edd29b1559db3d4085a12477b7e92409d2ee8fe69b1566e330a558
  Stored in directory: /home/david/.cache/pip/wheels/91/28/0d/f4eb606d38276836237d6dc2abf094241e6db5682a126e0389
  Building wheel for pyscreeze (PEP 517) ... done
  Created wheel for pyscreeze: filename=PyScreeze-0.1.27-py3-none-any.whl size=12891 sha256=234edc389e2225a8c2fdf64431eb0a092c618c8ec832009989f7c9b4e33041e1
  Stored in directory: /home/david/.cache/pip/wheels/f7/91/eb/c0fa176c095c77460a579ef339f24a377474b041e5543d1a00
  Building wheel for python3-Xlib (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/david/whatsapp/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nvgwm6ep/python3-Xlib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nvgwm6ep/python3-Xlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ah0gdsnx
       cwd: /tmp/pip-install-nvgwm6ep/python3-Xlib/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for python3-Xlib
  Running setup.py clean for python3-Xlib
  Building wheel for pyperclip (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/david/whatsapp/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nvgwm6ep/pyperclip/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nvgwm6ep/pyperclip/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ltci15ar
       cwd: /tmp/pip-install-nvgwm6ep/pyperclip/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for pyperclip
  Running setup.py clean for pyperclip
  Building wheel for pyrect (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/david/whatsapp/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nvgwm6ep/pyrect/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nvgwm6ep/pyrect/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-quq271gf
       cwd: /tmp/pip-install-nvgwm6ep/pyrect/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for pyrect
  Running setup.py clean for pyrect
Successfully built pymsgbox pyscreeze
Failed to build pyautogui wikipedia PyTweening mouseinfo pygetwindow python3-Xlib pyperclip pyrect
Installing collected packages: PyTweening, pyperclip, python3-Xlib, mouseinfo, pyrect, pygetwindow, pymsgbox, Pillow, pyscreeze, pyautogui, soupsieve, beautifulsoup4, certifi, urllib3, idna, chardet, requests, wikipedia, pywhatkit
    Running setup.py install for PyTweening ... done
    Running setup.py install for pyperclip ... done
    Running setup.py install for python3-Xlib ... done
    Running setup.py install for mouseinfo ... done
    Running setup.py install for pyrect ... done
    Running setup.py install for pygetwindow ... done
    Running setup.py install for pyautogui ... done
    Running setup.py install for wikipedia ... done
Successfully installed Pillow-8.2.0 PyTweening-1.0.3 beautifulsoup4-4.9.3 certifi-2021.5.30 chardet-4.0.0 idna-2.10 mouseinfo-0.1.3 pyautogui-0.9.52 pygetwindow-0.0.9 pymsgbox-1.0.9 pyperclip-1.8.2 pyrect-0.1.4 pyscreeze-0.1.27 python3-Xlib-0.15 pywhatkit-4.8 requests-2.25.1 soupsieve-2.2.1 urllib3-1.26.5 wikipedia-1.4.0
(whatsapp) ➜  whatsapp pip uninstall pywhatkit
Found existing installation: pywhatkit 4.8
Uninstalling pywhatkit-4.8:
  Would remove:
    /home/david/whatsapp/lib/python3.8/site-packages/pywhatkit-4.8.dist-info/*
    /home/david/whatsapp/lib/python3.8/site-packages/pywhatkit/*
Proceed (y/n)? y
  Successfully uninstalled pywhatkit-4.8
(whatsapp) ➜  whatsapp git clone https://github.com/Ankit404butfound/PyWhatKit
Cloning into 'PyWhatKit'...
remote: Enumerating objects: 742, done.
remote: Counting objects: 100% (277/277), done.
remote: Compressing objects: 100% (187/187), done.
remote: Total 742 (delta 162), reused 156 (delta 90), pack-reused 465
Receiving objects: 100% (742/742), 1.74 MiB | 2.68 MiB/s, done.
Resolving deltas: 100% (419/419), done.
`

**To Reproduce**
1. Go to https://pypi.org/project/pywhatkit/
2. Click on 'the clipboard sign next to the pip command in the white box at the top'
3. See error above

**Expected behavior**
A normal pip installation

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser:  chrome

**Additional context**
Installation was successful following the installation guide here: https://github.com/Ankit404butfound/PyWhatKit/wiki
I'm working inside a venv

**Comment by Ankit404butfound** [comment]
Since it's Ubuntu, try pip3 install pywhatkit.
