### ISSUE TITLE
Error sending an instant message with 'tab_close' param.

### ISSUE THREAD

**Issue by asim-sansi** [Ankit404butfound/PyWhatKit#84]
Calling pywhatkit.sendwhatmsg_instantly() with tab_close argument results in an error.

**Error Message**
`
   elif browser.lower() not in ["chrome", "firefox", "brave", "opera"]:  
   AttributeError: 'bool' object has no attribute 'lower'
`

1. import pywhatkit
2. pywhatkit.sendwhatmsg_instantly("+9*****", "Hello", 10, True)

**Expected behavior**
A message should be delivered to the recipient and after the  message is sent the tab should close.

 - OS: Windows 10, version - 21H1
 - Browser: Firefox 89.0.2 (64-bit)
 - python: Python 3.7.4
 - pip: pip 20.2

**Comment by Ankit404butfound** [comment]
Try this `pywhatkit.sendwhatmsg_instantly("+9*****", "Hello", 10, tab_close=True)`

**Comment by aaryanrr** [comment]
Hey @asim-sansi , this has been fixed in the latest release. We recommend that you upgrade pywhatkit to the latest verion.

**Comment by asim-sansi** [comment]
it seems using a keyword argument as @Ankit404butfound mentioned solves the issue.
