### ISSUE TITLE
Add 'delay' parameter to 'sendwhatmsg' function.

### ISSUE THREAD

**Issue by leadersheir** [Ankit404butfound/pywhatkit#9]
Imposing a 60-second delay seems redundant. Add a delay parameter to the 'sendwhamsg' function and instead of hardcoding 58 seconds to time.sleep(), use time.sleep(delay).

**Comment by Ankit404butfound** [comment]
> Imposing a 60-second delay seems redundant. Add a delay parameter to the 'sendwhamsg' function and instead of hardcoding 58 seconds to time.sleep(), use time.sleep(delay).

Along with adding time.sleep(delay) some additional lines have to be changed too. I will update the library with proper delay functionality asap. :-)

**Comment by leadersheir** [comment]
I made some changes to the function and tested it out with 0 errors. I've madea pull request. Care to take a look at it?

**Comment by Ankit404butfound** [comment]
Merged!

**Comment by Ankit404butfound** [comment]
> I made some changes to the function and tested it out with 0 errors. I've made a pull request. Care to take a look at it?

Library has been updated.
