### ISSUE TITLE
Image to text (OCR feature)

### ISSUE THREAD

**Issue by psychoSherlock** [Ankit404butfound/PyWhatKit#90]
# OCR ( Optical Character Recognition ) in pywhatkit
#### We could use any python modules that supports OCR, but the one I like most is pytesseract  as its very accurate and uses google's OCR engine.

**Comment by aaryanrr** [comment]
Hey @psychoSherlock , It would be a good feature, we'll see what can be done.

**Comment by aaryanrr** [comment]
Hey @psychoSherlock, OCR can be an useful feature but most of the offline solutions that we found are slow and it'll require some heavy dependencies. We really want this module to be lightweight. So we are not planning on including this feature. Thanks for your valuable suggestion!

**Comment by codewithpom** [comment]
@aaryanrr Just use an API that we will make in flask or fast-api

**Comment by aaryanrr** [comment]
That would require a better server.

**Comment by codewithpom** [comment]
why ?

**Comment by psychoSherlock** [comment]
> why ?

I think he's right (@aaryanrr)making a server just for OCR detection may arise many security issues, which is not something we could handle, and also it costs much to buy a server that's faster, resourcefull for OCR detection and with a high network bandwidth

**Comment by codewithpom** [comment]
@psychoSherlock Just host on repl.it or heroku and use a module with Google OCR and please tell me what are the security issues. :slightly_smiling_face:

**Comment by psychoSherlock** [comment]
> @psychoSherlock Just host on repl.it or heroku and use a module with Google OCR and please tell me what are the security issues. :slightly_smiling_face: 


Pywhatkit is currently just a non profit small community right, so I belive it would be had for them to host and manage these servers. As @aaryanrr said it's better if we kept it light weight

Why bother for hosting if paid APIs are already available, [read here](https://rapidapi.com/blog/top-5-ocr-apis/). 

Or if u wanna use a offline version, use [pytesseract](https://pypi.org/project/pytesseract/)

**Comment by codewithpom** [comment]
Python-tesseract uses Google OCR hence even it uses internet.

**Comment by aaryanrr** [comment]
> > @psychoSherlock Just host on repl.it or heroku and use a module with Google OCR and please tell me what are the security issues. 🙂
> 
> Pywhatkit is currently just a non profit small community right?, so I belive it would be hard for them to host and manage these servers. As @aaryanrr said it's better if we kept it light weight
> 
> Why bother for hosting if paid APIs are already available, [read here](https://rapidapi.com/blog/top-5-ocr-apis/).
> 
> Or if u wanna use a offline version, use [pytesseract](https://pypi.org/project/pytesseract/) 🙃

Yep correct. And offline use requires the installation of the Tesseract OCR Engine and adding it to the path so that is some extra steps required.
