### ISSUE TITLE
unable to locate element in python selenium script

### ISSUE THREAD

**Issue by mitchelstarc101** [Ankit404butfound/PyWhatKit#91]
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="frm_text_username_#1id"]"}

unable to locate the id with my python selenium code

**Comment by aaryanrr** [comment]
Hey @mitchelstarc101 , this issue is not relevant with the Project. For help related to certain topics you can join our discord server [here](https://discord.gg/62Yf5mushu).
