### ISSUE TITLE
Send image using sendwhats_image function for Mac

### ISSUE THREAD

**Issue by claytonmaciel** [Ankit404butfound/PyWhatKit#95]
I made the code below and added it in **sendwhats_image** function. And it works on mac.

The code:

```
if system().lower() == "darwin":
         width, height = pg.size()
         pg.click(width / 2, height / 2)
         os.system(f"osascript -e 'set the clipboard to (read (POSIX file \"{img_path}\") as JPEG picture)'")
         time.sleep(wait_time)
         pg.hotkey("command", "v")
         time.sleep(3)
         pg.press('enter') 
```

My environment:
**[OS: MacOs Big Sur 11.4]
[Browser: Google Chrome 91.0.4472.114]
[IDE: PyCharm CE 2021.1.3]**

I leave my contribution for discussion. Thank you very much!

**Comment by aaryanrr** [comment]
Hey, @claytonmaciel , thanks for your valuable contribution. I guess this only works for JPEG files. Is there any support for PNG, GIF's or Videos?

**Comment by claytonmaciel** [comment]
I tried to find the solution in several ways using terminal and clipboard on Mac (clipboard, pasteboard, pgcopy etc). But unfortunately, it only worked in the following way on my computer. The code worked for every type of file (PNG, GIF's or Videos) in my environment.

```
if system().lower() == "darwin":
        pg.hotkey("command", "option", "space")   #open finder
        time.sleep(2)
        pg.hotkey("command", "shift", "g")   #open go to folder
        time.sleep(2)
        pg.typewrite(img_path)   #find the file         
        pg.press("enter")
        time.sleep(2)
        pg.hotkey("command", "c")   #copy the selected file
        time.sleep(2)
        pg.hotkey("command", "w")   #close finder
        time.sleep(2)
        web.open('https://web.whatsapp.com/send?phone=' + phone_no + '&text=' + caption)    
        time.sleep(wait_time)
        width, height = pg.size()
        pg.click(width / 2, height / 2)   #emphasis in WhatsApp web window, only Mac
        pg.hotkey("command", "v")   #paste the selected file
        time.sleep(3)
        pg.press('enter')                                    
```

My environment:
**[OS: MacOs Big Sur 11.4]
[Browser: Google Chrome 91.0.4472.114]
[IDE: PyCharm CE 2021.1.3]**

I hope I have contributed. Thank you very much!

**Comment by aaryanrr** [comment]
Oh I see. We'll include both the solutions, for JPEG files the first solution will be used and for others the second one. Thanks a lot for this valuable contribution.
